### ISSUE TITLE
Check the object constellation data

### ISSUE THREAD

**Issue by WimDeMeester** [DeepskyLog/DeepskyLog#130]
---

Author Name: **David Erzeel** (@DavidErzeel)
Original Redmine Issue: 122, http://redmine.deepskylog.org/issues/122
Original Date: 2009-12-24

---

In since DSL 3.6, an administrator can check to see if the objects are in the
right constellations. You first select a number of objects (e.g. Search Object,
select a constellation, execute query) and then you go to Administration/Check
objects, and you will get a result back.

**Comment by WimDeMeester** [comment]
---

Original Redmine Comment
Author Name: **David Erzeel** (@DavidErzeel)
Original Date: 2009-12-24T09:37:13Z

---

Constellations AND-ARA are done.

**Comment by TomCorstjens** [comment]
constellations ARA - CYG are done : 12 issues found.
[Constell.xlsx](https://github.com/DeepskyLog/DeepskyLog/files/2687259/Constell.xlsx)
NOT YET corrected

**Comment by TomCorstjens** [comment]
All constellations are verified, in total 61 objects have a conflict with constellation and/or coordinates. 

See attached: 
[Constell_errors.xlsx](https://github.com/DeepskyLog/DeepskyLog/files/2687711/Constell_errors.xlsx)

Someone interested to check in database and correct? JefDeWit?

**Comment by TomCorstjens** [comment]
database checked and corrected by Jef. 
Most conflicts were genuine borderline objects on 2 constellations. 
Issue closed.
