### ISSUE TITLE
When changing an instrument, both Focal length and F/D should be filled.

### ISSUE THREAD

**Issue by WimDeMeester** [DeepskyLog/DeepskyLog#300]
Html 5 complains that both the focal length and F/D should be filled when changing an instrument.

Issue by AS.

**Comment by TomCorstjens** [comment]
I noticed the same problem today when changing instrument information

**Comment by WimDeMeester** [comment]
In the laravel version of DeepskyLog, the focal length is calculated automatically from the F/D and vice versa. This means that it is impossible that one of the two is not filled in.
