### ISSUE TITLE
Sandqvist / Sanduleak / ...

### ISSUE THREAD

**Issue by WimDeMeester** [DeepskyLog/DeepskyLog#329]
The Sa list has both some Sandqvist objects (Sa xxx) and some other objects (Sa xx-xxx). Sand objects: Sand = Sandqvist, and not e.g. Sanduleak?

I propose not to use abbreviations for these catalogs, but just use the full name:
- Sanduleak
- Sandqvist
- ...

Someone of the database team should look into this: @DeepskyLog/deepskylog-database 

Issue by AS.

**Comment by TomCorstjens** [comment]
both catalogi have been cleaned and do not exist any more.
