### ISSUE TITLE
Search buttons scroll out of main page window

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#355]
In 5.0 release, the left section with search buttons move out of the window, when scolling down. 
Preferred to keep them a STATIC section of the main page, to make sure you can at any time enter a seach action.
![zoekbutton](https://cloud.githubusercontent.com/assets/12647470/8708384/e2d802c2-2b3b-11e5-96fa-dadfeb8f91ec.PNG)
Also, the buttons should better be of equal dimensions - and with some space in between (look&feel)

**Comment by WimDeMeester** [comment]
To be fixed together with issue 446.
