### ISSUE TITLE
Green shortcut Icons "search" become VERY big when screen is made smaller

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#356]
(1) In release 5.0 on main page, when the window is made smaller, the shortcut icons for fast searching are automatically made smaller: 
![small1](https://cloud.githubusercontent.com/assets/12647470/8708514/b7e76980-2b3c-11e5-9eec-a5e01eed589a.PNG)
But when the window is such small that the 4 icons do not fit on one line, they are displayed under each other, and they become VERY big: 
![small2](https://cloud.githubusercontent.com/assets/12647470/8708538/da981344-2b3c-11e5-843c-c88ecb496661.PNG)

(2) Also the icons on the top, change from full-text links, towards partial text & partial icons (not user-friendy): 
![iconssmall](https://cloud.githubusercontent.com/assets/12647470/8708629/781f1e46-2b3d-11e5-9c89-3c95a54a868a.PNG)
Should be either always text, either all being an icon when made small.

(3) when screen is made even smaller, the DSL logo picture drops dowm and the search field becomes a full-screen wide field - not user/display friendly.
![searchfield](https://cloud.githubusercontent.com/assets/12647470/8708736/0af836ee-2b3e-11e5-806f-44819a16869e.PNG)

**Comment by WimDeMeester** [comment]
1) I will make two columns with 3 icons. When this issue is fixed, you will see something like this:
![issue356](https://cloud.githubusercontent.com/assets/7261529/9449786/2b94a992-4aa5-11e5-99da-b25cd22f2943.png)

Is this OK?

**Comment by WimDeMeester** [comment]
2) It is not possible to add text for all entries. I propose to leave the icons for the 'Home'-link and for the 'Messages'-link. Is this acceptable @TomCorstjens ?

![issue356-2](https://cloud.githubusercontent.com/assets/7261529/9450023/927647f0-4aa6-11e5-9674-4cde26c15599.png)

**Comment by TomCorstjens** [comment]
Both suggestions are OK, good fixes! 
When read and implemented, you can close the issue.
