### ISSUE TITLE
Twilight info not available on main screen

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#358]
The twilight information of the actual day is no longer available in 5.0: 
![schemeringnew](https://cloud.githubusercontent.com/assets/12647470/8709213/207be36e-2b41-11e5-8662-49c25f549e05.PNG)

In the current (older 4.x release), this is displayed as: 
![schemering](https://cloud.githubusercontent.com/assets/12647470/8709138/a18d4d68-2b40-11e5-9cea-3f930914a431.PNG)

Or the link with ClearOutside can be used here, since it contains same valuable twilight information.

**Comment by TomCorstjens** [comment]
Issue is resolved when logged in. 
Question: do we also want to display this for visitors / non-logged users?

**Comment by WimDeMeester** [comment]
We can not display this for visitors / non-logged users, because we need the standard location for this...

**Comment by TomCorstjens** [comment]
OK, then let's close the issue. Logical functionality.
