### ISSUE TITLE
New observation cannot be logged via Menu bar

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#362]
No menu selection is available to create a new observation.
Suggested to 
- Rename the option "Nieuwe waarnemingen" by "Recente waarnemingen"
- Add the option 'Mijn waarnemingen"

![newobs](https://cloud.githubusercontent.com/assets/12647470/8710282/f9c2b18c-2b48-11e5-8956-98c9ebecaed8.PNG)

**Comment by WimDeMeester** [comment]
Hi Tom,

Is it possible that you are logged in as administrator, and not as a normal user. The administrator does not have all the options. As normal user, there is a option 'My observations'.

**Comment by TomCorstjens** [comment]
Indeed, I was not logged in at all. Hence no possibility to record a new observation. -> Functionality is OK
when logged in, there is indeed the possibility to log a new observation via the BUTTON "nieuwe waarneming", but it is not possible to initiate a "nieuwe waarneming" via the menu "Overzicht".

**Comment by TomCorstjens** [comment]
This function was relocated to the Menu option "Toevoegen" -> waarneming. OK
