### ISSUE TITLE
Login screen does not foresee "loss of password" support

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#367]
When the Login button is clicked, a popup window does appear. 
Missing: a link what to do in case you have lost your password (auto-email to developers)?
Missing "close-cross" in corner to close this windows

![login](https://cloud.githubusercontent.com/assets/12647470/9066199/7acfdf38-3ad6-11e5-81f6-ca18150e6d47.PNG)

**Comment by WimDeMeester** [comment]
Will work on this, together with issue #444

**Comment by WimDeMeester** [comment]
![lostpassword1](https://cloud.githubusercontent.com/assets/7261529/11906557/ba7bcb26-a5cd-11e5-9303-62770bb87440.png)
![lostpassword2](https://cloud.githubusercontent.com/assets/7261529/11906555/ba74fab2-a5cd-11e5-9c9c-d18e06d03c7d.png)
![lostpassword3](https://cloud.githubusercontent.com/assets/7261529/11906556/ba7875de-a5cd-11e5-8fa1-45a320639157.png)
