### ISSUE TITLE
"New observations" gives very long list, not limited to e.g. 20 observations - reduces performance & speed

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#370]
When logged in and via "overzicht" -> "nieuwe waarnemingen"
The full database is displayed, as a very very long list of hunderds of logs. This reduces significantly the performance and usability.
There must be a limit of e.g. 20 observations per page (as with release 4.x)

**Comment by TomCorstjens** [comment]
Similar bug when "My Observations" in Compact modus is selected 
-> Displays ALL my observations and is downloading all sketches

NOTE: When "List" is selected, similar but after downloading all info, then the TableSorter filters the first 10 observations. 

ISSUE: it seems that first all observation details are loaded, and only then the first "x" observations are filtered. In case the connection is slow or with heavy data, it appears that unfiltered data are displayed. 

SOLUTION: can FIRST the filtering be done, and THEN the download of observation details?

**Comment by WimDeMeester** [comment]
I have implemented a temporary fix. The main problem is the very slow implementation of javascript in Internet Explorer. This makes the tablesorter crash. 

Fix implemented:
+ If the table contains more than 3500 entries, the tablesorter is not used.
+ If Internet Explorer is used, the tablesorter is not used for tables with more than 500 entries.

This will make sure the browser does not crash anymore. The speed can still be improved, but this is a major work package. I will open a new issue for this. See issue #422
