### ISSUE TITLE
Delete Instrument is overkill for a separate column

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#377]
In the overview of instruments, there is a separate column for "delete" instrument. 
This only is possible when no observation was made with this instrument. Hence it is rare <1% that this will be used, and take too much space on the screen as a separate column. 
![deleteinstrument](https://cloud.githubusercontent.com/assets/12647470/9067247/969afe2c-3adc-11e5-8575-1744df44e1ac.PNG)

Suggested improvement: 
- Place the "trashbin" icon in an existing column, e.g. "active" column
- hide this "delete" column by default.

**Comment by TomCorstjens** [comment]
When selecting "choose columns, the "auto" modushas the "delete" column disabled, but it is enabled in the view....
![auto_instrument](https://cloud.githubusercontent.com/assets/12647470/9072160/e1429b2a-3af9-11e5-8211-bf519e5c7369.PNG)

**Comment by PieterjanDeconinck** [comment]
Regarding your 2nd message, this looks like normal behaviour. There is no need to change the selections based on the autofunction. It is on the other hand useful for the user that his choices are not changed, in case he decides not to use the "Auto" function.

**Comment by TomCorstjens** [comment]
When loading "my instrument" page, the column delete instrument is not present by default. 
Issue has been solved with one of the previous releases. 👍
