### ISSUE TITLE
New instrument creation: Focal length of F/D value is not mandatory

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#379]
When creating a new instrument, it can be saved just by creating a "name" and entering the diameter.
Solution: 

The selected TYPE of instrument should trigger the MANDATORY info-field: 
- For binocular or finder: fixed magnification
- for others: Focal length or F/D ratio

!! would even be better that by default the focal length or F/D is shown, and when a bino / Finder is chosen, this changes into fixed magnification.

**Comment by WimDeMeester** [comment]
I agree that it should not be possible to enter a new instrument without a fixed magnification, focal length and F/D.

> !! would even be better that by default the focal length or F/D is shown, and when a bino / Finder is chosen, this changes into fixed magnification.

I don't think we want that... Some antique telescopes also have a fixed magnification and larger finderscopes can have a changeable magnification (and need an eyepiece), so the focal length should be given.

Implementing the check that the focal length, F/D and fixed magnification are not empty at the same time.

**Comment by WimDeMeester** [comment]
It is not longer possible to create an instrument without F/D, focal length and fixed magnification now. See screenshot of the laravel version of DeepskyLog:

![image](https://user-images.githubusercontent.com/7261529/74544922-4578b680-4f48-11ea-89b2-ee519be2b682.png)
