### ISSUE TITLE
Moving column(s) and "choosing" columns is not syncronised

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#381]
Starting situation at e.g. location menu:
- "Delete" column is last column (before number of obs)
  ![locbug1](https://cloud.githubusercontent.com/assets/12647470/9091228/5675c7dc-3b9f-11e5-8c61-5bdcdae13f8f.PNG)

Step 1: "Delete" colums is moved upfront
![locbug2](https://cloud.githubusercontent.com/assets/12647470/9091264/8ed96a48-3b9f-11e5-9c92-51ec55b4c484.PNG)

Step 2: At menu "choose column", the colum "delete" is hidden. 
BUG: the wrong column (here: standard location) is hidden, the "delete" column is still visible.
![locbug3](https://cloud.githubusercontent.com/assets/12647470/9091336/fd9cab3e-3b9f-11e5-8e9c-eec4b9d9cf95.PNG)

**Comment by TomCorstjens** [comment]
Further testing identfied this is not only with the "delete" column, but with all moved columns.
ISSUE: when moving a column, the order is not updated in the drop-down menu "choose column". This gives problems when hiding columns from that menu.

**Comment by WimDeMeester** [comment]
This problem is fixed in the laravel version of DeepskyLog.
