### ISSUE TITLE
Menu "choose column" does not disappear when clicking randomly in window

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#382]
The drop-down menu "choose column" is expected to disappear when random clicking anywhere in the window. This does not function as expected, the menu only disappears when the button is clicked again.
Not user-friendly.
![buttoncolumn](https://cloud.githubusercontent.com/assets/12647470/9091524/01e54b82-3ba1-11e5-9cb0-2dff6da44f3b.PNG)

**Comment by TomCorstjens** [comment]
The menu even blocks other menu's chosen: 
![hidemashup](https://cloud.githubusercontent.com/assets/12647470/9092270/5f58fd32-3ba5-11e5-92bc-8a0918b3a49e.PNG)

**Comment by TomCorstjens** [comment]
@WimDeMeester can this be resolved (easily?) with a next release?

**Comment by WimDeMeester** [comment]
Fixed in the laravel version of DeepskyLog.
