### ISSUE TITLE
Column "standard location" cannot be (de)selected in menu "choose columns"

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#384]
Screenshot: 
![stdloclist](https://cloud.githubusercontent.com/assets/12647470/9092189/dddb9e54-3ba4-11e5-826b-3012dd07a565.PNG)
The column "standard location" cannot be (de)selected. Should be possible, since it rarely is changed and takes quite some space.

**Comment by WimDeMeester** [comment]
Fixed already in the laravel version of DeepskyLog.
