### ISSUE TITLE
Add atlas "Interstellarium Deepsky Atlas" to Public List

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#385]
In analogy with the "Taki Star Atlas", can the "Interstellarium Deepsky Atlas" be added as a public list?
The ISDA is a very commonly used atlas for experienced observers (even more than Taki)

**Comment by SkyNomad** [comment]
The Interstellarum Atlas database list is not publicly available, but we could ask.

According to http://www.oculum.de/sites/deepskyatlas/site/en/dsa.asp?content=faq, 
The Interstellarum Atlas is based on both "Eye & Telescope", cross-checked with the "Deep-Sky-Liste".
see: 
http://www.eyeandtelescope.com/
http://www.deepskybeobachtung.de/downloads/dsl9.pdf

The latter guys are very nice to include a link to DeepskyLog on their webpage! See http://www.deepskybeobachtung.de/index.php/deep-sky-liste-dsl#Download

It would become a huge list however: 9599 galaxies, 117 clusters of galaxies, 508 groups of galaxies, 1903 open clusters, 181 globular clusters, 536 asterims, 58 star clouds, 530 bright galactic nebulae, 526 dark nebulae, 755 planetary nebulae, 122 quasars ...
Isn't that too much for a list?

**Comment by TomCorstjens** [comment]
Correct, this would be a huge list ... 
on the other hand, the "Taki Star atlas" also is a List, with 2952 objects (created by Jan VA). 

QUESTION: Is there another easier way to solve this, than via a list?

**Comment by TomCorstjens** [comment]
Closing the issue since there is no real solution to the request
