### ISSUE TITLE
Display all observation locations (from all users) in a specified radius

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#386]
Idea from RolfV on Astroforum.nl
Concept is to "discover" nice dark locations nearby, that have already a proven trackrecord of good observations.

**Comment by SkyNomad** [comment]
Including data like SQM of NELM-statistic.
Link to SQM-chart websites?

**Comment by WimDeMeester** [comment]
I think we can not do this taking into account the privacy of our users. Closing the tickets.
