### ISSUE TITLE
Deepskylog kaart (pdf) does not open

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#387]
When clicking either "Overzicht", "Zoeken", "Detail" next to "Deepskylog kaart (pdf)", a new browser window opens, but no pdf (neither in browser nor in default .pdf reader)

Issue tested on v5 in Firefox 40.0.02, Opera 31.0, Safari.
Issue does not exist in previous version (pop-up screen opens with request to either open or save)

**Comment by TomCorstjens** [comment]
Idem in Explorer 9 and 10: HTTP 500 Internal Server error.
This might be due to the 'TEST' environment?

**Comment by TomCorstjens** [comment]
Works fine in the LIVE version, tested on IE9.0.8

**Comment by SkyNomad** [comment]
Idem dito in Firefox & Opera: works just fine!
