### ISSUE TITLE
Show or delete extra info: "-" sign nearly invisible

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#388]
on top of screen "object details", there is either shown "+ Show or hide extra information...", or a tiny "-" symbol. The latter is almost too small to find.

In general, it is not very clear that by clicking ">", only that info appears, an by clicking the description, fields can be selected.
Since there are only 4 blocks, My preference is to remove the "+ Show or hide extra information", and only keep the selection by description button, and remove the selection ">". This simplifies the interface and keeps full functionality.

**Comment by TomCorstjens** [comment]
Related to issue #374 - to be solved together.

**Comment by WimDeMeester** [comment]
Will remove the buttons in the laravel version. All information will always be shown.
