### ISSUE TITLE
Interactive atlas: no stars anymore..

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#389]
'interactive atlas' is a great concept!
- v5 no longer displays stars, only database objects
- no zooming possible on iOS (two-fingers zoom entire screen, not the map)

**Comment by WimDeMeester** [comment]
The test database does not include all the stars. Only stars up to magnitude 5 are in the test database. This should be checked and tested after the 5.0 release.

**Comment by TomCorstjens** [comment]
also the instructions "O" - "Z" - "D" for "Overzicht / Zoek / Detail" do not work.

![interactiveatlas](https://cloud.githubusercontent.com/assets/12647470/9311731/838ac3b2-4518-11e5-8ce4-833e2c0a68f9.PNG)

**Comment by WimDeMeester** [comment]
Hey @TomCorstjens and @SkyNomad 

Can you try again on the released version? I see the stars and can use the O - Z - D keys.

**Comment by TomCorstjens** [comment]
Have tested it today, and yes it works fine !!!

**Comment by SkyNomad** [comment]
Roger, Firefox & Opera are happy as well !!
