### ISSUE TITLE
tab 'nearby objects' opens object info, but does not select 'nearby objects'

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#391]
on screen "observation" / "object details", you can select "nearby objects <object>". This opens the object screen, with on top the selection boxes "object details", "object ephemerides", "nearby objects", "object observations", in accordance to the latest selection of those boxes. i.e. if previously "ephemerides" was shown, it does NOT show "nearby objects".
This is counterintuitive. Either the title has to be changed to "object details", or the selectionbox on objectdetails has to be changed to "nearby objects" only.
This is not a new issue: behaviour of v5 is identical to previous version.

**Comment by WimDeMeester** [comment]
All information is shown in the laravel version of DeepskyLog.
