### ISSUE TITLE
Rename list does not work

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#393]
When renaming an observing list, a confirmation box opens to confirm that list name has changed.
Name change is aso confirmed on the page title "Overzicht geselecteerde objecten <listname>"
BUT, in reality, the old name persists in the drop-down selection list. So next time you look for it, you have to keep looking for the old name.

This routine was changed for v5

Removal of a lists works just fine.

**Comment by WimDeMeester** [comment]
Another problem with the lists:
When another list has the same name (but is made by another user), the objects of the other list are also shown...

**Comment by WimDeMeester** [comment]
Fixed the two problems.
