### ISSUE TITLE
Observing location and instrument : why always on top?

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#394]
As in previous version, I don't fully understand why the "observing location" and "instrument" selection are always on top. The function is usefull when looking at object info (to calculate contrast reserve), but it is annoying that if changed, you always move back to the main screen (observing list in previous version, welcome screen in new version). Counterintuïtive.

**Comment by WimDeMeester** [comment]
Date can also be moved to the ephemerides of the day / night.

**Comment by WimDeMeester** [comment]
To be addressed in the laravel version of DeepskyLog.

**Comment by WimDeMeester** [comment]
In the new version of DeepskyLog that is being developed, the location and instrument will not be on top of the page anymore.  It will be at the places where the setting is needed.
