### ISSUE TITLE
eyepieces: uniform description

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#398]
No priority, but: is it still possible to revise & make uniform eyepiece list? Current naming is quite random.

Preferrable naming is:
focal length / mm / brand / subbrand or type

e.g.
22 mm TeleVue Nagler
7 mm Kasai Or
3 - 6 mm TeleVue Nagler Zoom

**Comment by WimDeMeester** [comment]
Some people prefer to use specific names for their eyepieces (for example the handgranate for the 31mm Nagler). I propose to show the given name for the eyepieces of the owner and for all other observers, we can create a generic name.

**Comment by WimDeMeester** [comment]
Add a brand and type to the eyepieces. Observers need to select a brand and a type for new eyepieces, or when editing an old eyepiece.  The observer can still choose the name for the eyepiece, but the observer will only see this name for his own eyepieces. Other observers will see a generic name, consisting of focal length / mm / brand / type. 
This will not fix the problem for the old eyepiece, but in the future, the problem should be less and less obvious.
