### ISSUE TITLE
message link to "realisations" does not work

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#400]
I was happy to receive a-following message on deepskylog: 

![realisatie](https://cloud.githubusercontent.com/assets/12213599/9299769/ad71fdca-44bf-11e5-9f5d-5cd35f29e00d.png)

unfortunately, the link does not work: 
"
The requested URL /test/test/index.php was not found on this server.
Apache/2.2.15 (Scientific Linux) Server at www.deepskylog.org Port 80
"

**Comment by WimDeMeester** [comment]
Very strange message. I looked in the code and there is nowhere a message sent with the link to deepskylog.org/test/test/. I did find a problem however. The name of the observer is not passed to the method that sends the mails when a new star is accomplished. I will change this before the 5.0 release.
