### ISSUE TITLE
Object details: public list info is wrongly aligned & not readible

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#404]
For popular objects that appear in many public lists (e.g. M92), the object details contain partial, wrongly aligned and not readible, "mashed up" info on the public lists.

![p](https://cloud.githubusercontent.com/assets/12647470/9305464/dd5818b2-44f1-11e5-9661-924da519caff.PNG)

**Comment by WimDeMeester** [comment]
Fixed together with #412
