### ISSUE TITLE
Reporting problem (redirect Github): no clear instructions + quid rights?

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#406]
when a user wants to report a problem, he is redirected to GitHub:
![probleem](https://cloud.githubusercontent.com/assets/12647470/9305842/bd56b188-44f4-11e5-831f-8d6b4b3f580a.PNG)

This immediately pop-ups the Github interface, and gives two issues: 
- can everyone create an issue? also a "visitor?
- no instructions on how to log an issue in Github. Requires at least some basic instructions e.g. via screen popup with step-by-step info.

**Comment by WimDeMeester** [comment]
You need at least a GitHub account to add issues to GitHub.

**Comment by TomCorstjens** [comment]
Meaning 90% of users cannot do anything... 
Needs a better solution, for example two options in the drop-down 
* "rapporteer probleem" -> send email to developers, or even a separate email adress for the responsible for bug resolution
* "GitHub Issues (admin)" -> current functionality (redirect to Github)

**Comment by TomCorstjens** [comment]
Since I'm now more aware of "software" development: Github is about the "default" in coding. 
Also the past 3 there has not been any external person logging an issue. 

Decided to close the issue.
