### ISSUE TITLE
Introduce auto-calculation of "Vergroting" when logging new observation

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#407]
Currently the applied magnification has to be entered manually (not mandatory). 
The used eyepiece is a mandatory field and contains always the focal length
-> proposal to auto-calculate the magnification when selecting an eyepiece. 

![vergroting](https://cloud.githubusercontent.com/assets/12647470/9306286/92bd079e-44f7-11e5-819a-236f3ebce83c.PNG)

Proposed by RolfV on Astroforum.nl

**Comment by WimDeMeester** [comment]
Closing the issue.

**Comment by WimDeMeester** [comment]
Live on the server as DeepskyLog 5.0.1.
