### ISSUE TITLE
Layout of screen for "new observation" is not adequate

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#408]
SERIOUS ISSUE from user experience point of view:
The screen layout for recording a new observation in this release is not adapted and a de-provement in comparison with 4.x release. All fields are displayed below each other, whereas this should be visible in one screen (as 4.x release).
.
The 5.0 release: 
![newobslayout](https://cloud.githubusercontent.com/assets/12647470/9306421/83fcf2fe-44f8-11e5-8bdb-63f41aafb5b3.PNG)

The 4.x release: 
![newobslayoutv4](https://cloud.githubusercontent.com/assets/12647470/9306425/87cb5524-44f8-11e5-8f02-85c7c139e419.PNG)

**Comment by WimDeMeester** [comment]
I strongly disagree with this issue. Making everything visible on one screen will - again - introduce a lot of bugs with smaller screens, like tablets and phones. The only way to solve these issues is to put everything below each other.

**Comment by TomCorstjens** [comment]
OK understood from functionality point of view. 
Though this will be for sure a feedback issue from usability point of view. To be followed up after release.
