### ISSUE TITLE
Column names missing when scrolling down in observation list

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#411]
Blank fields appear on the upper side of the screen when scrolling down in e.g. an observation list.
These are the "SORT" fields, but the column information does not remain visible.

Either: 
- do not display "Blank sorting fields" when scrolling down
- display the column info above the blank sorting fields, also when scrolling down.

![sortbarobs](https://cloud.githubusercontent.com/assets/12647470/9311445/832d4ff4-4516-11e5-8df4-54f9a60757b6.PNG)

**Comment by WimDeMeester** [comment]
In the laravel version, the sorting fields are not longer shown.
