### ISSUE TITLE
Observations details missing / not displayed with button "Object details -> "show observations"

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#412]
When an object is searched, there is a button to display also the related observations:
![obs_list](https://cloud.githubusercontent.com/assets/12647470/9311891/a6fd282a-4519-11e5-9dcd-8a1df1849c21.PNG)

Then the "List" display is activated, but only 3 columns are loaded: constellation, observer and date.
Observation details are not visible, nor it is possible to click on DT / MO / LO to load details of a specific observation.
Displayed columns cannot be chosen.

![obs_list2](https://cloud.githubusercontent.com/assets/12647470/9311951/073bc070-451a-11e5-8294-48a21cb00867.PNG)

When "Compact" display is activated, no recording details of the observation (and no sketches) are visible.

![obs_list3](https://cloud.githubusercontent.com/assets/12647470/9311958/11801518-451a-11e5-9038-3db17c8770ed.PNG)

**Comment by WimDeMeester** [comment]
The problem occurs at the moment the method 

addTableColumSelector

is executed for the nearby objects. Will investigate further.

**Comment by WimDeMeester** [comment]
The second table also follows the selected columns from the first. It is possible to show everything, but then we have to select the 'Object Name' columns.

**Comment by WimDeMeester** [comment]
Fixed together with #404
