### ISSUE TITLE
Unclear colour code for display "Object Ephemerides"

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#416]
When selecting object details, there is a button for object efemeriden for the "default" observation location:
![efemeriden1](https://cloud.githubusercontent.com/assets/12647470/9313819/69b51778-4525-11e5-9695-32002c14945c.PNG)

The resulting table is difficult to understand: 
- need to add some instructions / explanations how to read this table
- requires a legenda what the different colors mean

Screenshot:
![efemeriden2](https://cloud.githubusercontent.com/assets/12647470/9313838/8a89d2ae-4525-11e5-9a02-4a0cbce44219.PNG)

**Comment by WimDeMeester** [comment]
Add a legenda in the laravel version of DeepskyLog.

**Comment by WimDeMeester** [comment]
The laravel version of DeepskyLog already has the extra information:

![image](https://user-images.githubusercontent.com/7261529/75784829-15604e80-5d63-11ea-9a7e-ac1fd8a9c36b.png)
