### ISSUE TITLE
Observation Sorting on "Instrument": use of name -> change to instrument diameter

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#417]
Within a list of observations for one object, when sorting on the column "Instrument", the NAME of the instrument is used for sorting. This has no real added value... (last instrument is e.g. WO 4" refractor and the Zelfbouwkijker...)

Better: the instrument DIAMETER should be the value being sorted. Then the user can see : 
- what is minimum diameter to observe the object?
- what are the smaller telescopes already used for an object
- What is the biggest telescope used (and open the relevant observation)

**Comment by WimDeMeester** [comment]
This is coupled with issue #481.

**Comment by WimDeMeester** [comment]
Hi @rolfvandervleuten 

I guess that this problem will be solved when you implement the new datatables?
