### ISSUE TITLE
Link "Most Popular Objects" loads ALL objects => website non-responding

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#422]
When clicking via Menu "Overzicht" -> Popular Objects, a sorted overview is loaded of ALL objects (before the TableSorter comes into action, see Issue #370)
![popularobj](https://cloud.githubusercontent.com/assets/12647470/9365937/ae900b88-46b4-11e5-8df7-24490307b4ff.PNG)

After about 1 minute, the website crashes: 
![popularobj2](https://cloud.githubusercontent.com/assets/12647470/9365951/bd6f5640-46b4-11e5-9266-7463a24ee843.PNG)

PRIORITY: for the Launch, disable this link!! Will cause complaints.

**Comment by TomCorstjens** [comment]
Identical for Menu "Overview" -> "Nieuwe Observaties" 
=> Loads ALL observations in the database (when you are a new user) -> website crashes

**Comment by WimDeMeester** [comment]
I have implemented a temporary fix. The main problem is the very slow implementation of javascript in Internet Explorer. This makes the tablesorter crash. 
Fix implemented: 
+ If the table contains more than 3500 entries, the tablesorter is not used.
+ If Internet Explorer is used, the tablesorter is not used for tables with more than 500 entries.

This will make sure the browser does not crash anymore. The speed can still be improved, but this is a major work package. I will open a new issue for this.

**Comment by TomCorstjens** [comment]
Problem also occurs with Firefox, see feedback from Rem on Astroforum:

na het opvragen van nieuwe waarnemingen, krijg ik na enige tijd deze foutmelding:
![speed](https://cloud.githubusercontent.com/assets/12647470/9566345/24e73720-4f02-11e5-9a1b-94fd79423696.PNG)
Ik gebruik Firefox 40.0.3 op Windows 8.1 .

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens ,

The newest release (now online) includes changes by @rolfvandervleuten in the way the tables are loaded and handled. It is the ambition to change all tables in the way that the 'Most popular objects' now shows the table. Can you test if the table is now fast enough?

Thanks!

**Comment by WimDeMeester** [comment]
Hi @rolfvandervleuten 

I still found a problem... When you are at the 'View popular objects' page, you cannot use the menu anymore...

**Comment by WimDeMeester** [comment]
According to @TomCorstjens , the speed is already much better. @TomCorstjens is the speed acceptible? We plan to move all tables to the table you see here.
