### ISSUE TITLE
Check possibility to filter on "active" column (checkbox ON / OFF)

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#424]
Verify whether it is possible to develop a filter in the column "Active" , to allow selecting only active OR only non-active items (e.g. Eyepieces)

![oculairs_actief](https://cloud.githubusercontent.com/assets/12647470/9366720/407dfe98-46b9-11e5-8e55-94df8fdbe8ed.PNG)

**Comment by WimDeMeester** [comment]
Closed by rolfvandervleuten
