### ISSUE TITLE
Incorrect Object Catalogue "AC" (is double star)

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#428]
Only 1 observation for catalogue "AC" (double star)

![cata_ac](https://cloud.githubusercontent.com/assets/12647470/9367714/77d3de7a-46bf-11e5-9906-a7de9bf6adf4.PNG)

==> remove catalogue + replace observation

**Comment by SkyNomad** [comment]
"AC" stands for "Alvin Clark's Catalogue of double stars". This is often named "AGC", but we already have AGC for the Abell Catalog of Rich Clusters of Galaxies. 
In Simbad, search "** AC 01", and you'll find HD 1641 / SAO 53827 / ...
Simbad has 20 entries from this catalogue, and it is reported to have 81 objects. Maybe we can include them all?

**Comment by TomCorstjens** [comment]
Do not agree, if we have only 1 object, and only 1 log of that object ... on a total of 80000 logs... better to obsolete that catalogues from usability point of view.

GENERAL: Better to have one central issue, else there is scattering for the database developer.

**Comment by TomCorstjens** [comment]
Catalogue AC has been removed. 
Object AC1 had 2 observations, they were linked to corresponding HD catalogue

[11 - AC catalogue.xlsx](https://github.com/DeepskyLog/DeepskyLog/files/784129/11.-.AC.catalogue.xlsx)

Issue closed
