### ISSUE TITLE
Incorrect Object Catalogue "Acamar" (is name of triple star)

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#429]
![cata_acamar](https://cloud.githubusercontent.com/assets/12647470/9367806/02d02dbc-46c0-11e5-987b-92c8cfa27eff.PNG)

==> remove catalogue + replace observation

**Comment by SkyNomad** [comment]
Tom,

I'm currently also checking the catalogues. I had my comments offline for the moment, but propose to open 1 single issue to table all comments related to catalogues. If a problem can be fixed, it's best to fix it immediately in the database.

DeepskyLog "catalogs" include much more than only catalogs. In many cases, an object is attributed to the first person/team to observe it, and is best known / often referred to by that name. If there is more than one object, I think we need the catalogues. If there is only one object, we do need to be able to find it by alternative naming. For example, 61 Cygni is known as "Bessel's star", and it if we currently search for "Bessel 's" or "Bessel's" (but not "Bessel's star), we con find the object. I propose to also include such naming issues in the table.

I'll immediately open a central issue for database corrections.

**Comment by TomCorstjens** [comment]
Better to have one central issue, else there is scattering for the database developer. 
I also stopped after the "b" because there were many cases with single-entry catalogues.

**Comment by TomCorstjens** [comment]
Following objects have been removed from database: 
![image](https://cloud.githubusercontent.com/assets/12647470/23082493/e5848bf0-f559-11e6-84f0-a842f751eeb9.png)

**Comment by TomCorstjens** [comment]
In order to cleanup the catalogi: 

Following objects have been removed from database:

![image](https://cloud.githubusercontent.com/assets/12647470/23082538/11e850f0-f55a-11e6-8607-d002810d8d51.png)

**Comment by TomCorstjens** [comment]
In order to cleanup the catalogi:
Following objects have been removed from database (starting B and C)

![image](https://cloud.githubusercontent.com/assets/12647470/23084820/91c38dbc-f564-11e6-95ab-93342991bf33.png)

**Comment by TomCorstjens** [comment]
Cleanup catalogi : 
Changes objects from catalogus item into named object. 

![image](https://cloud.githubusercontent.com/assets/12647470/23105187/21435b26-f6db-11e6-9876-a661c61f5066.png)

**Comment by TomCorstjens** [comment]
Cleanup catalogi :
Changes objects from catalogus item into named object, and/or replaced by an offician name like PK for e.g. Dddm 1 (source Simbad).

![image](https://cloud.githubusercontent.com/assets/12647470/23105573/ae02549e-f6e1-11e6-9a9f-c4434665b2e6.png)

**Comment by TomCorstjens** [comment]
Cleanup catalogi: 
Removed following catalogi - objects. 
![image](https://cloud.githubusercontent.com/assets/12647470/23186528/c259b840-f887-11e6-855b-953709446d43.png)

Completed the Dias catalogus with Dias 1 - 4 - 5 - 6 - 7 - 8
(needed correction after failed csv file)

**Comment by TomCorstjens** [comment]
Cleanup Catalogi: 
Removed or renamed objects to exclude them from catalogi.
![image](https://cloud.githubusercontent.com/assets/12647470/23189102/a6b66016-f891-11e6-97ca-d0fc7b8f04da.png)

Completed the Haffner catalogus (12 + 24)

**Comment by TomCorstjens** [comment]
- Expanded and completed the HuWe and HDW catalogi
- Cleanup HIPP catalogus
- Cleanup Ho catalogus (towards Hogg)

- Removed or renamed following objects to exclude them from catalogi.
![image](https://cloud.githubusercontent.com/assets/12647470/23283856/90b5ae0a-fa28-11e6-9b91-32c576508a3f.png)

**Comment by TomCorstjens** [comment]
- Expanded and completede Hubble catalogus
- Clarified K catalogue with relevant PK references
- Removed or renamed following objects to exclude them from catalogi:

![image](https://cloud.githubusercontent.com/assets/12647470/23321049/da5dbf56-fadd-11e6-9cae-bfc44d0708c6.png)

**Comment by TomCorstjens** [comment]
Removed or renamed following objects to exclude them from catalogi:

![image](https://cloud.githubusercontent.com/assets/12647470/23334832/900cb68a-fba7-11e6-9685-9300ce5e65f0.png)

**Comment by BobHogeveen** [comment]
I notice there are a lot of double star catalogi cleaned up by this action. What are the criteria for having a catalogue in the DB?
Maybe the double star catalogi are not very well known, but all the ones that I have entered are officially included in WDS. Some examples:
ARG, the catalogue of F. Arglander
BAL, the catalogue of R. Baillaud
BLL, the catalogue of R.S. Ball
And so a lot more, all present in WDS

**Comment by TomCorstjens** [comment]
First, no objects are removed that have an observation in DSL or that part of a public list. That is a basic principle. So be sure: your logs have not disappeared.
Next, objects with prefix that is not common with other objects (doubtful as genuine catalogue), are renamed by changing entire reference as name and making catalogue field empty. This goes beyond stars and double stars. Idem for e.g. Maffei. And for many many starclusters and asterisms. If there are only few objects, lets say 3 - 5 entries, then it is not a catalogue. This will be changed into 'alternative name' in case there is also a reference to a more popular catalogue. 
A catalogue is a LARGE collection of objects.This is no exact science. But an effort to keep deepskylog user-friendly.Any suggestions are welcome. When you want specific objects to become a catalogue, AND the catalogue is currently incomplete, you are kindly asked to help completing the database and prepare the CSV file.
Tom


Sent from my Samsung S6 edge
-------- Oorspronkelijk bericht --------Van: BobHogeveen <notifications@github.com> Datum: 26/02/17  12:22  (GMT+01:00) Aan: DeepskyLog/DeepskyLog <DeepskyLog@noreply.github.com> Cc: TomCorstjens <tom.corstjens@telenet.be>, Assign <assign@noreply.github.com> Onderwerp: Re: [DeepskyLog/DeepskyLog] Incorrect Object Catalogue "Acamar" (is name of triple star) (#429) 
I notice there are a lot of double star catalogi cleaned up by this action. What are the criteria for having a catalogue in the DB?

Maybe the double star catalogi are not very well known, but all the ones that I have entered are officially included in WDS. Some examples:

ARG, the catalogue of F. Arglander

BAL, the catalogue of R. Baillaud

BLL, the catalogue of R.S. Ball

And so a lot more, all present in WDS

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeepskyLog/DeepskyLog","title":"DeepskyLog/DeepskyLog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeepskyLog/DeepskyLog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BobHogeveen in #429: I notice there are a lot of double star catalogi cleaned up by this action. What are the criteria for having a catalogue in the DB?\r\nMaybe the double star catalogi are not very well known, but all the ones that I have entered are officially included in WDS. Some examples:\r\nARG, the catalogue of F. Arglander\r\nBAL, the catalogue of R. Baillaud\r\nBLL, the catalogue of R.S. Ball\r\nAnd so a lot more, all present in WDS"}],"action":{"name":"View Issue","url":"https://github.com/DeepskyLog/DeepskyLog/issues/429#issuecomment-282549147"}}}

**Comment by TomCorstjens** [comment]
As an example: 
There were 4 objects in DSL for ARG - each with one observation.
They were changed from [ "ARG" + "4" ] into "ARG 4" as being a **named object**.
You can still find them directly when typing "ARG 4" at the field "search" query.

![image](https://cloud.githubusercontent.com/assets/12647470/23340610/9421e280-fc39-11e6-980c-1d86e95c904b.png)

The ARG reference can be found in Simbad and contains in total 100 objects: 
![image](https://cloud.githubusercontent.com/assets/12647470/23340565/d23db0d6-fc38-11e6-8231-3faca49aac18.png)

Here we have two options: 
(1) either we enter the FULL catalogue in DSL, 
(2) either we only use named objects and do not consider the few entries as catalogue items.
My judgement here was to go for option 2. In case someone wants to work out the entire ARG catalogue as a FULL catalogue in DSL: please feel welcome.

**Comment by TomCorstjens** [comment]
For completion: I use the SIMBAD website as source reference.

==> The entries BALL and BLL could not be found in Simbad as catalogue.
Nevertheless the observation was retained as a "named object".

Deepskylog should remain a user-friendly interface; that is a key principle. 
We should strive to use the most common and popular catalogu as key references. For example, many planetary nebulae with special names were changed into their reference in PK. Their original special name (e.g. HuBi, HuDo) was changes into "alternative name" to keep track.
Same for double stars, where the SAO, HD, Struve etc.  catalogi are used a key reference.

**Comment by BobHogeveen** [comment]
Thanks for the explanation! The situation is clear.
I agree that option 2 is best for these objects of which only a few will be observed.
What is the best option for entering new objects like a BAL double star when it is observed?
Enter it with the SAO or HD number and then give it the alternative name 'BAL nnnn'?

**Comment by TomCorstjens** [comment]
Yes, please enter with the common catalogue SAO or HD or struve and use alternative name for the less common catalogue entry.

Thanks for the help!

**Comment by TomCorstjens** [comment]
For completion: there are some catalogi that I did not cleaned up. 

Example: **the double star catalogus HJ**
There are many thousand of objects in this catalogue. In Deepskylog already 174 objects were entered. 
Here I did not started the cleanup because ... 
(1) it is a hell of a work :-) 
(2) since there are so many entries and logs, there is a genuine need to retain HJ as a catalogue.

It's not an exact science, but hope this clarifies the ongoing work.

![image](https://cloud.githubusercontent.com/assets/12647470/23340833/4163cf28-fc3d-11e6-848b-58f26c0f245e.png)

**Comment by BobHogeveen** [comment]
Yes, I understand ;-)
There are a few other quite common double star catalogues like STT, STTA (like STFA and STFB), BU, SHJ and DUN to name a few.
Please let me know which can remain as catalogue. 
For the more obscure ones I can help changing the names to regular catalogue numbers like SAO and enter the other name as alternative name, if you like.

**Comment by TomCorstjens** [comment]
I'm not that known with star catalogues; you have a better judgement on that. If you can work out a proposal of most common catalogues for double stars, please indicate them here so I will definitely retain them and use them in case of corrections.

When you can help in changing names: that would be of a great help.  Really... a huge work.
Let me first perform the "quick 'n dirty" cleanup, next we can formalise and harmonise in a second round.

**Comment by TomCorstjens** [comment]
Real-time example: catalogue ODE
There is only one object: 
![image](https://cloud.githubusercontent.com/assets/12647470/23340978/f98c2936-fc3f-11e6-8c22-81f794d9703e.png)
and: 
![image](https://cloud.githubusercontent.com/assets/12647470/23340988/1610fef6-fc40-11e6-9e71-c76ccc6af9a7.png)
There are 2 logs - so they really must be retained. 

Next step: copy-paste coordinates in simbad.
![image](https://cloud.githubusercontent.com/assets/12647470/23340995/31718440-fc40-11e6-9c29-a74337f3f5e5.png)

This gives: 
![image](https://cloud.githubusercontent.com/assets/12647470/23341004/52ada9fe-fc40-11e6-8f7d-1167bc5ec1d9.png)

From the 7 potential identifiers in below, I will chose the most "common" one: SAO 44659
Why not BD+48 2129  ... because this catalogue is less used in DSL. 

And this results in: 
![image](https://cloud.githubusercontent.com/assets/12647470/23341037/fb296406-fc40-11e6-9a64-9df46419261e.png)

The logs are retained, the name is changed into SAO 44659 and the ODE 11 is retained as alternative name. 
For completion: the applied code is 
NN;ODE 11;SAO;44659
AN;SAO 44659;;ODE 11

**Comment by TomCorstjens** [comment]
A bookcase example of wrong use of the catalogi function: 

![image](https://cloud.githubusercontent.com/assets/12647470/23341199/31a52108-fc43-11e6-9fff-ebc5783349d7.png)

Omicron is recognised as a catalogue ....

**Comment by BobHogeveen** [comment]
Yes, these are good examples of things that should be cleaned up...
Let me check what is left in the DB as catalogue of double stars and make a proposal for a few really 'usefull' catalogues and then clean up the rest!

**Comment by TomCorstjens** [comment]
- Expanded and completede Peimbert catalogus and linked with PB and PC references
- Linked Pegasus I cluster to individual members
- Removed or renamed following objects to exclude them from catalogi:

![image](https://cloud.githubusercontent.com/assets/12647470/23342119/d6dfbcee-fc54-11e6-8d27-adcd567c4abf.png)

**Comment by BobHogeveen** [comment]
From historical point of view and based on the fact that names from the major historical double star catalogues are still used as primary identifier of the objects, I suggest that the catalogs up to Espin (ES) are kept as catalogue in DSL. The more recent catalogs do not contain many pairs which can be observed by amateurs. (see list below).
We did a lot of work to get the STF catalogue in DSL and it is not really possible to do that for the others.

Note: There are almost 800 catalogs included in WDS... ;-)

![image](https://cloud.githubusercontent.com/assets/22999023/23342115/cf15096a-fc54-11e6-8583-f7513f60f569.png)

**Comment by TomCorstjens** [comment]
OK thanks. 

...

That is a major amount of work.

**Comment by BobHogeveen** [comment]
Name OS 532 can be removed, it is an incorrect way of spelling for the name STT 532.
(OS stands for Otto Struve, but the catalogs is now officially named STT).

I will remove this alternative name from Beta Aql, ok?

**Comment by TomCorstjens** [comment]
Okay.

**Comment by TomCorstjens** [comment]
Completed the Pismis catalogue

Removed or renamed following objects to exclude them from catalogi:

![image](https://cloud.githubusercontent.com/assets/12647470/23342713/a4d67426-fc5f-11e6-9cbf-2457f54c3cb6.png)

**Comment by BobHogeveen** [comment]
Name South 798 can be removed from Epsilon Peg. The official catalog name is S 798, which is already there. For some reason I cannot remove alternative name South 798 myself (?)

**Comment by WimDeMeester** [comment]
@BobHogeveen I will invite you to our slack channel, so you can have a chat-like conversation with Tom (and others).

**Comment by TomCorstjens** [comment]
Physically removed following objects (no observations, no lists): 

![image](https://cloud.githubusercontent.com/assets/12647470/23590617/b7133000-01e3-11e7-843b-e9120b5020ca.png)

Changes Catalogi Objects into Named Objects and/or alternative names: 
![image](https://cloud.githubusercontent.com/assets/12647470/23590616/b027e6a0-01e3-11e7-9079-083e02fd63a3.png)

**Comment by TomCorstjens** [comment]
THE LAST ONES !! 

Changes Catalogi Objects into Named Objects and/or alternative names:

![image](https://cloud.githubusercontent.com/assets/12647470/24060666/8fd3ffae-0b54-11e7-8765-1542c77acd21.png)

Physically removed following objects :

![image](https://cloud.githubusercontent.com/assets/12647470/24060688/a9d902a0-0b54-11e7-81a4-32aff7404779.png)

**And this concludes the first wave of database cleanup!**

**Comment by TomCorstjens** [comment]
This is the remaining list of CATALOGI: 

![image](https://cloud.githubusercontent.com/assets/12647470/24060799/1b44fc46-0b55-11e7-87ea-89dcb8cc7f0a.png)

**Comment by TomCorstjens** [comment]
For reference and back-up: all main csv files used.


[Catalogi Clean-up - CSV files.zip](https://github.com/DeepskyLog/DeepskyLog/files/851651/Catalogi.Clean-up.-.CSV.files.zip)

ISSUE CLOSED!
