### ISSUE TITLE
Speed improvements

### ISSUE THREAD

**Issue by WimDeMeester** [DeepskyLog/DeepskyLog#431]
This issue is a master issue to discuss speed problems in DeepskyLog. Just add speed problems to the list below:
- All data is read and put in a table. We should only download the data which is visible (this includes sorting and pagination). This is a major work package! Temporary fix in #422 .

**Comment by SkyNomad** [comment]
In addition, the final layout chosen is not optimal.

While reading the data, the screen looks like this:

![list1](https://cloud.githubusercontent.com/assets/12213599/9566702/dc533352-4f0f-11e5-84cf-e5b47def6246.png)


When finished, it has chosen a column width that make the "instrument description" take up two lines:

![list2](https://cloud.githubusercontent.com/assets/12213599/9566713/42912354-4f10-11e5-9970-d74a9c7b2c9f.png)


Maybe the "instrument" field should be limited in length, or to be replaced by "aperture" in this list.

**Comment by rolfvandervleuten** [comment]
I think the next datatables update will improve speed significantly. 
We could also use caching of observations in server memory

**Comment by WimDeMeester** [comment]
New in version 5.0.19.

![datatables](https://cloud.githubusercontent.com/assets/7261529/10756130/5b1320de-7ca2-11e5-9f73-72947bdbf548.png)

**Comment by WimDeMeester** [comment]
The laravel version of DeepskyLog is build with jquery datatables, should be faster and will not have the strange behavior of the changing table. Closing this ticket, because in the laravel version, we focus on jquery datatables and (hopefully) speed.
