### ISSUE TITLE
Dark Blue Screen Background at first startup

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#443]
DeepskyLog 5.0 just released!
The release (both on www.deepskylog.org and on www.deepskylog.be) has at first a dark blue background, which is hard to read! In addition, scrollbar right is missing. When refreshing the page turns white! This was not the case with the test version ??? 
Issue on Firefoax 40, NOT on iOS 8 !!

![blue screen](https://cloud.githubusercontent.com/assets/12213599/9566276/655dfa44-4eff-11e5-8c67-4f8d500de771.png)

**Comment by TomCorstjens** [comment]
This has to do with the CACHE of your computer. Press F5 and its solved. 
Don't think we can do anything from the website.

**Comment by WimDeMeester** [comment]
Indeed, we can not do anything to solve this... The old stylesheet is still in the browser cache and is apparently not reloaded automatically.

**Comment by rolfvandervleuten** [comment]
you could rename the stylesheet, then it would not be read from cache

**Comment by WimDeMeester** [comment]
That's indeed a possibility, but we should think to change the stylesheet for every release then... I'll implement this.

**Comment by WimDeMeester** [comment]
Live on the server as DeepskyLog 5.0.2.
