### ISSUE TITLE
Changing chosen atlas requires double entry of password

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#444]
Feedback from svdwal on Astroforum - and confirmed via testing in DSL5.0: 

 in Iets waar ik me al een poos aan erger: als je een andere atlas of zo instelt moet je ook je wachtwoord aanpassen.  Wat handig zou zijn is dat je bij de zoekfuncties opgeeft voor welke atlas je de functie uitvoert. Ik heb diverse atlassen en voor kleine objecten als PN's gebruik ik een andere atlas dan voor grote objecten. Daarnaast zijn er de gespecialiseerde atlassen voor Herschel objecten, dubbelsterren enz. Elke keer de instellingen aanpassen is dan vervelend. Liever een dropdown box met atlaskeuze, met een standaard ingevulde waarde die je snel kan aanpassen.
 edit: het is vervelender. Als je wat aanpast, maar niet het wachtwoord opgeeft, dan gooit DSL je aanpassing weg. Heb je het voor niets gedaan.

**Comment by TomCorstjens** [comment]
Responded that it is not mandatory to CHANGE the password, but not user friendly that the password should be entered, and especially double entry.

**Comment by WimDeMeester** [comment]
I will also revamp the settings page. The different categories of settings will be in different tabs. This makes the settings page more clear.

**Comment by WimDeMeester** [comment]
I started working on this. I will set up the test server to show the progress.

**Comment by WimDeMeester** [comment]
Can be tested on http://www.deepskylog.org/test/

**Comment by WimDeMeester** [comment]
Fixed in DeepskyLog 5.0.20.
