### ISSUE TITLE
Number of displayed lines (10 / 20 / 30 / 40)

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#445]
Feedback from Rem on Astroforum: 
Nice combo for 10, 20, 30 or 40 lines per page. But I also want to select 1000 again, just like before.

**Comment by rolfvandervleuten** [comment]
what is desired?
 - a dropdown item for 1000, maybe also add 100 and 500. - quick easy fix
 - a way to manually enter a number - less easy fix

**Comment by TomCorstjens** [comment]
A drop-down of 100, 250 and 500 would indeed be a nice function (quick-fix). Max on 40 is quite low.
The numeric selection can ben an enhancement on long-term.

**Comment by rolfvandervleuten** [comment]
values in dropdown are adjusted

manual input remains on the list as nice-to-have

**Comment by TomCorstjens** [comment]
>           values in dropdown are adjusted
> manual input remains on the list as nice-to-have

Values were NOT adjusted. 

@WimDeMeester can this be set at 10 - 25 - 50 - 100  please?

**Comment by WimDeMeester** [comment]
In the laravel version of DeepskyLog, the option are 10, 25, 50, 100, and 500.
