### ISSUE TITLE
Homepage: layout improvements

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#446]
On my laptop (Firefox 40, windows titlebar on the right & with not-so-good screen quality), the DeepskyLog home page looks like this:

![fullscreen](https://cloud.githubusercontent.com/assets/12213599/9566394/09cb35c0-4f04-11e5-9d68-c603a064f549.png)

Primary Issue: The text of the five icons on the bottom is not readable. I put my windows titlebar on the bottom for this screenshot, but even with the titlebar to the right, it is not fully readable. The new image is very nice, but too large.

Other issues:
* color of top bar (dark grey on black) is not easy to read.
* to improve layout of the left search block:
* separate & make the three search options equally large (or remove from home page, while we now have the two giant loupes)
* layout "Zoeken" en "maan / zon" as a true title
* moon image may be larger

**Comment by WimDeMeester** [comment]
I worked on the left menu. Is this something you have in mind?

![screen shot 2015-09-05 at 22 25 39](https://cloud.githubusercontent.com/assets/7261529/9701144/1d677eea-541d-11e5-859d-a2fa1929d40d.png)

Things still to do:
+ Make the left menu fixed.
+ Add tooltips to the icons, so the observers can see what the icons mean when the hover with the mouse over the icons.
+ Make it possible to remove the new logo. This will only be possible for the registered observers and will reappear every time a new version is released. I will add a way to see the new things in every new release, but I still have to think how to do it.

**Comment by SkyNomad** [comment]
Yes, this is already cleaner!

Search box is perfect.
Maybe remove "huidige maan" description?
Or split the section: one with all moon data, one with sun data?
I can keep on being picky on layout, if you want ;-)

On the top right, we can change a date. Is it the intent to change the Moon / Sun information when that date changes (it doesn't). If it is: schouldn't "date" also be in the left pane?

**Comment by WimDeMeester** [comment]
When we change the date (top right), the sun / moon information also changes (for me, on my personal test server and on the production server). The date is visible in the left pane, under the title 'Moon / Sun'.

**Comment by WimDeMeester** [comment]
+ Removed the 'Current moon' description.
+ Made the left menu fixed. This fixes issue #355

**Comment by WimDeMeester** [comment]
The logo is only shown the first time the page is loaded after there was a DeepskyLog update. Added a link to the What's new page to the image.

**Comment by SkyNomad** [comment]
Thanks for changing the left menu!

**Comment by SkyNomad** [comment]
Hy Wim,

I see you removed the big logo - maybe it's the best solution,
It's a shame because it was very nice - maybe you can convince the author to make a smaller one?

The scans of object drawings are not all square. For observations, that doesn't matter, but is it possible to show only a central square on the home page?

**Comment by WimDeMeester** [comment]
Hi  @SkyNomad ,

The big logo is still visible the first time an observers visits the home page after an update. At this moment, this is at least twice a week ;-) Not registered visitors still see the logo every time they visit DeepskyLog.

Can you open a new issue for the second part of your remark (the not square drawings)?
