### ISSUE TITLE
Add location: "search for" and map do not work

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#448]
On "Toevoegen - waarneemplaatsen", the function "Zoek Locatie" and the map screen do not work in the released version.

They worked (and still work) perfectly in the test version !!

**Comment by SkyNomad** [comment]
EDIT: they DID work after allowing DeepskyLog to use my location and refreshing the screen!

It may be because my default windows setting does not allow transfer of my location. That would explain why no map was shown, but still, the search + map should also work with that privacy setting on?

**Comment by TomCorstjens** [comment]
I've tried to reproduce this issue, as I also had problems in the past. 

Running on MS Edge and having disabled that google can use my location (see screenshot), the functionality still works fine. 
![image](https://cloud.githubusercontent.com/assets/12647470/23075721/dd4fd4ec-f53d-11e6-9776-f4a3ec4229a4.png)

Perhaps a patch  has been sent out to solve browser settings by default?
Suggest to test in Chrome and Firefox, and if no problem -> close issue

**Comment by WimDeMeester** [comment]
Tested in the laravel version of DeepskyLog in Safari, chrome, and firefox on Mac and Edge in Windows. Everything works fine.
