### ISSUE TITLE
Observer details do not refresh

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#449]
After changing default observing location, the "observer details" page does not fully refesh. The four tabs no longer work. Refeshing browser window does not help. (firefox 40.0.2)

![observer details](https://cloud.githubusercontent.com/assets/12213599/9566670/d767c274-4f0d-11e5-9f74-ef9e44343fdd.png)

After going back to home page & then clicking back to the "observer details" page, everything is just fine again.

**Comment by WimDeMeester** [comment]
I'll start working on this.

**Comment by WimDeMeester** [comment]
I tried to reproduce this, but for me, everything works in firefox 40.0.3. Can you confirm that you still have this problem?

**Comment by WimDeMeester** [comment]
Should be fixed in DeepskyLog 5.0.20.
