### ISSUE TITLE
Total object number doesn't change when making a selection of a list

### ISSUE THREAD

**Issue by PieterjanDeconinck** [DeepskyLog/DeepskyLog#453]
In the designator for page numbers, the total number of objects (between brackets) does not change when a selection of the original list is made.

![issue453](https://cloud.githubusercontent.com/assets/14027778/9567321/a3518c9a-4f26-11e5-88c2-5c264e0e6b02.JPG)

In this examle of the list of Messier objects a selection of 3 objects is made. The total number still shows 110.

**Comment by PieterjanDeconinck** [comment]
In addition: by using the button 'Alle resultaten toevoegen aan lijst', all 110 objects of the original list are added to my own list. It would be more logical when only the selected objects are added to the list. Otherwise all objects need to be added one by one...

**Comment by rolfvandervleuten** [comment]
fixed by datatables-2
