### ISSUE TITLE
Import observations does not recognise all double observations

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#460]
OK, accidentally imported the same .csv with 66 observations twice... (I know it's stupid)

Both in the first and second import, the import function correctly rejected 9 observations.
But the second import recognised only 22 observations as double observations, altough the file was completely identical!

I'll have to delete the observations now -> see next issue!

**Comment by WimDeMeester** [comment]
This was a problem with the comparison of the sqm and limiting magnitude values. This should not happen again in DeepskyLog > 2018.2.
