### ISSUE TITLE
Sorting object list: always back to default sorting

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#468]
When changing an object's place in a list, there are two issues:

1) it takes quite some time (8 seconds) before the new location has been accepted, and the (unnecessary) box to confirm the move pops up (similarly, deleting an object also takes a lot of time)

2) after clicking away the pop-up box, the list changes back to default sorting (i.e. on entry number) and starts back at entry number one). I'd much prefer that the sorting / filter remains

**Comment by rolfvandervleuten** [comment]
fixed by datatables-2
