### ISSUE TITLE
Nice to have Jef de Wit: sort observations on diameter of the instrument

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#481]
In the list with observations, you can sort on telescope, but the sort is alphabetically on the name. This is not usefull. Being able to sort and filter on diameter is much better.

**Comment by WimDeMeester** [comment]
Two parts:
+ Remove the search on instrument name when searching for observations.
+ Sort on instrument diameter and not on name in the lists (in the new DataTables @rolfvandervleuten ?).
