### ISSUE TITLE
'Highest X' columns in search results no longer contain data

### ISSUE THREAD

**Issue by PieterjanDeconinck** [DeepskyLog/DeepskyLog#482]
When searching for objects ('Zoek' > 'Zoek object'), columns 'Hoogste alt.', 'Hoogst van', 'Hoogst tot' and 'Hoogst rond' no longer contain data. All these columns are filled with '-'.

**Comment by WimDeMeester** [comment]
Hi @PieterjanDeconinck , are you sure you are logged in? To be able to calculate the values, a location is needed. If there is no location selected (or when you are not logged in), you will only see '-'. I can see the correct values in DeepskyLog.

**Comment by PieterjanDeconinck** [comment]
Yes, this occurs when I'm logged in. I did some additonational tests. Apparently it only bugs on some queries... I can't say why it doesn't work in these cases.
For example: 'Waargenomen:  Enkel objecten die ik reeds heb waargenomen' + 'Type: Planetaire nevel' returns only '-' in these columns.

Tested on both Chrome and IE. This is when logged in and a location is selected.

**Comment by WimDeMeester** [comment]
Indeed, this query also doesn't show the 'max altitude' for me. Thanks, now I can start fixing the bug ;-)

**Comment by WimDeMeester** [comment]
Available in DeepskyLog 5.0.11.
