### ISSUE TITLE
Footer not fixed on all pages

### ISSUE THREAD

**Issue by PieterjanDeconinck** [DeepskyLog/DeepskyLog#483]
The footer (the bar on the bottom of the page) is not fixed on all pages. A lot of pages show the bar randomly in the middle of the page. See screenshot for example. The footer should be fixed on the bottom of each page at all time. Or at least below the pages content.

![issue483](https://cloud.githubusercontent.com/assets/14027778/9888762/2224972e-5bf7-11e5-9eaf-9610d45bf48a.JPG)

Tested on both Chrome version 45.0.2454.93 and IE 11.

**Comment by WimDeMeester** [comment]
Closed.
