### ISSUE TITLE
Large header and footer (IE10) occupy ~40% of total screen.

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#497]
With current 10.0.x implementation, the top and botton bars are not dynamic and occupy almost half of the screen! 
![largebars](https://cloud.githubusercontent.com/assets/12647470/10123156/b2176382-6531-11e5-8ead-8b148ee2e193.PNG)
Suggested solutions: reduce size of icons / fields to keep them in small area, enabling larger area where content can be seen. Tx.

**Comment by WimDeMeester** [comment]
On smaller screens, this is indeed a problem... I will start with making the footer smaller.

**Comment by TomCorstjens** [comment]
We have a laptop with 15.3" screen. Is that considered a small screen? :-)   

----- Oorspronkelijk bericht -----

Van: "Wim De Meester" <notifications@github.com> 
Aan: "DeepskyLog/DeepskyLog" <DeepskyLog@noreply.github.com> 
Cc: "TomCorstjens" <tom.corstjens@telenet.be> 
Verzonden: Maandag 28 september 2015 14:33:45 
Onderwerp: Re: [DeepskyLog] Large header and footer (IE10) occupy ~40% of total screen. (#497) 



On smaller screens, this is indeed a problem... I will start with making the footer smaller.

**Comment by WimDeMeester** [comment]
On my 14'' laptop, I have a lot of space... Probably another IE bug... But anyway, the footer should already be smaller now. Is this already better?

**Comment by TomCorstjens** [comment]
yes, already better. 

Another suggestion to improve: put the copyright disclaimer at the screen bottom, in a smaller font size. This will create exta space when shrinking the window. 

----- Oorspronkelijk bericht -----

Van: "Wim De Meester" <notifications@github.com> 
Aan: "DeepskyLog/DeepskyLog" <DeepskyLog@noreply.github.com> 
Cc: "TomCorstjens" <tom.corstjens@telenet.be> 
Verzonden: Maandag 28 september 2015 16:05:03 
Onderwerp: Re: [DeepskyLog] Large header and footer (IE10) occupy ~40% of total screen. (#497) 



On my 14'' laptop, I have a lot of space... Probably another IE bug... But anyway, the footer should already be smaller now. Is this already better?

**Comment by rolfvandervleuten** [comment]
why is the footer fixed? why not just put it on the bottom of the screen, non-fixed?
On a page with a tabbed table it will hide the controls for paging, possibly making a user think there is only 1 page of results

**Comment by WimDeMeester** [comment]
On some pages, there is almost no content. On these pages, the footer will be drawn over the left menu. See #483.

**Comment by rolfvandervleuten** [comment]
If you change navbar-fixed-bottom in navbar-bottom, it will render non-fixed on the bottom of the page, also with short content pages. try it...

**Comment by WimDeMeester** [comment]
Indeed, this seems to work... This was a problem however in a previous version, where the left menu was also fixed.

**Comment by WimDeMeester** [comment]
Fixed in DeepskyLog 5.0.20.
