### ISSUE TITLE
Checkbox turns BLACK when clicking

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#498]
When clicking a checkbox (e.g. with selection of filters), the box backgroung color turns black.
![checkbox_black](https://cloud.githubusercontent.com/assets/12647470/10123178/ea2a9aae-6532-11e5-8f2f-84d1f8f7a561.PNG)

**Comment by WimDeMeester** [comment]
I guess you are also using IE 10 here?

**Comment by TomCorstjens** [comment]
yes, tested on IE10 

----- Oorspronkelijk bericht -----

Van: "Wim De Meester" <notifications@github.com> 
Aan: "DeepskyLog/DeepskyLog" <DeepskyLog@noreply.github.com> 
Cc: "TomCorstjens" <tom.corstjens@telenet.be> 
Verzonden: Maandag 28 september 2015 14:39:55 
Onderwerp: Re: [DeepskyLog] Ckeckbox turns BLACK when clicking (#498) 



I guess you are also using IE 10 here?

**Comment by TomCorstjens** [comment]
Most users are no longer running on IE10 browser - currently Microsoft Edge, Chrome, Firefox etc are common browsers.

Moreover: 
_On January 12, 2016, support ended for IE10 on Windows operating systems capable of running Internet Explorer 11, due to new support policies dictating that only the newest version of IE available for a supported version of Windows will be supported. IE10 will only be supported on Windows Server 2012[12][13] and Windows Embedded 8 Standard_

Suggested to close the issue.
