### ISSUE TITLE
Import Steve Gottlieb data

### ISSUE THREAD

**Issue by rolfvandervleuten** [DeepskyLog/DeepskyLog#520]
Import the data into our database

Individual objects are separated by a new line (paragraph symbol).  Each object begins with its NGC or IC number followed by a “|" (vertical bar).  On many objects I have multiple observations, so I also used a vertical bar to separate each observation.  The vertical bar is otherwise not used in any description, so you can easily search on it to parse all the observations.

There an entry for all 7840 objects in the NGC, including about 300 of which I have no observations.  After my last trip to Australia, that number is now cut in half, but it will be awhile before I’ve entered all of these.  I’ve only included IC objects for which I have notes, so this file is much smaller.

[NGC.txt](https://github.com/DeepskyLog/DeepskyLog/files/23978/NGC.txt)
[IC.txt](https://github.com/DeepskyLog/DeepskyLog/files/23979/IC.txt)

**Comment by WimDeMeester** [comment]
So I guess Steve Gottlieb gave us the right to add his observations into DeepskyLog? That would be wonderful!

**Comment by rolfvandervleuten** [comment]
he did, I also asked him to send his latest 150 NGC observations he made a couple of weeks ago in Australia. He needs to enter them into his own system first

**Comment by WimDeMeester** [comment]
It's a pity that there are no locations added to his observations... I'll have to think how to fix this for DeepskyLog.

**Comment by rolfvandervleuten** [comment]
I guess it won't be the same location for all observations. Maybe just add coordinates for 1 location, and add in the description there is precise location available.
