### ISSUE TITLE
Catalog screen layout incorrect

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#523]
when viewing the catalog screen, the object list is now UNDER the list of catalogs, which is unworkeable.

![catalog screen](https://cloud.githubusercontent.com/assets/12213599/11010825/5814d740-84e2-11e5-983e-e13a0eb760ef.png)

**Comment by WimDeMeester** [comment]
This part should indeed be rewritten.

**Comment by WimDeMeester** [comment]
This is a duplicate of issue #425

**Comment by WimDeMeester** [comment]
The new page:

![catalogs](https://cloud.githubusercontent.com/assets/7261529/12338717/5aab37b4-bb11-11e5-946c-9dc469484de4.png)
