### ISSUE TITLE
Only show diameter of the instrument in mm or inches in the new datatables

### ISSUE THREAD

**Issue by WimDeMeester** [DeepskyLog/DeepskyLog#525]
In the new datatables for a list of observations, we should only show the diameter of the instrument (and not the instrumentname) in mm or in inches. To decide whether we want to see the diameter in inches or in mm, we need a new setting in the settings page. We also need to add a field to the database to remember the mm or inches setting.

**Comment by rolfvandervleuten** [comment]
can we split this in:
-change column header / observation details
-support inches in instrument diameter + setting for inches / mm

how will we calculate a inch number ? 150 mm = 5.9 inch and not 6inch

will we also support inputting inches when adding a new instrument?

**Comment by WimDeMeester** [comment]
It is already possible to input the diameter in inches when adding a new instrument. 

I propose to just calculate the inches from the diameter in mm by dividing the diameter in mm by 25.4. This will indeed result in 5.9 inch for a 150mm telescope, but that's not a problem. Just make sure to only show one decimal number (show 5.9" instead of 5.905511811023622).

What do you mean with the first part of your question:

+ change column header / observation details

**Comment by rolfvandervleuten** [comment]
one part of the ticket is changing the observations result list so the instrument name is nog longer displayed and only the diameter in inches is displayed. The name of the instrument will be added to the details of the observation, when the "+" is clicked.

second part is checking for the setting and converting to inches. I'm not sure how to implement the database change and setting, so maybe better if you execute the second part.

**Comment by WimDeMeester** [comment]
I see. First focus on the first part of the job. I can guide you for the second part of the job, or I can do it myself. Maybe this is a nice example to learn how to implement the database changes.

**Comment by WimDeMeester** [comment]
This is done in the laravel version of DeepskyLog. As far as I remember, it is also done in the current version of DeepskyLog.
