### ISSUE TITLE
Length of list after selection - not remembered 

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#534]
When the number of viewed lines is changed e.g. with "Observers" from 10 to 30 (preferred view for a user), this is not remembered. When returning to this view, the default value of 10 is reset.
Same applies to all views where reduced views on lists apply: the default view length comes back again after further work and/or closing window.

**Comment by rolfvandervleuten** [comment]
Will be fixed by implementing datatables for the broken tables

**Comment by WimDeMeester** [comment]
The laravel version of DeepskyLog uses jquery datatables everywhere and does remember this settings.
