### ISSUE TITLE
Bizar copyright statement

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#541]
With current release, the copyright statement looks quite bizar ... 
![dsl_copy](https://cloud.githubusercontent.com/assets/12647470/11993909/ddc52aba-aa36-11e5-817f-4dac858581d5.PNG)
Looks like a typo or a wrong data conversion?

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens ,

I can not see this problem...

Which deepskylog installation do you use? 

www.deepskylog.be
www.deepskylog.org
www.deepskylog.nl
...

Are you logged in or not?
Which browser (and version are you using?

**Comment by TomCorstjens** [comment]
i'm using deepskylog.be and via MS Edge browser.

----- Oorspronkelijk bericht -----
Van: Wim De Meester <notifications@github.com>
Aan: DeepskyLog/DeepskyLog <DeepskyLog@noreply.github.com>
Cc: TomCorstjens <tom.corstjens@telenet.be>
Verzonden: Mon, 04 Jan 2016 10:23:31 +0100 (CET)
Onderwerp: Re: [DeepskyLog] Bizar copyright statement (#541)

Hi @TomCorstjens ,

I can not see this problem...

Which deepskylog installation do you use? 

www.deepskylog.be
www.deepskylog.org
www.deepskylog.nl
...

Are you logged in or not?
Which browser (and version are you using?

---

**Comment by WimDeMeester** [comment]
When not logged in, but also when logged in, using deepskylog.be and edge 20.10240.16384.0, I don't see the problem. Can someone else of the @DeepskyLog/deepskylog-developers test this who has Edge?

**Comment by WimDeMeester** [comment]
Just got a windows 10 update. Now using Microsoft Edge 25.10586.0.0. Still working. Are you looking at a specific page @TomCorstjens ?

**Comment by rolfvandervleuten** [comment]
Tested on Win10 with edge, cannot reproduce

**Comment by TomCorstjens** [comment]
cannot reproduce either ... considered isolated incident. Closed.
