### ISSUE TITLE
Double enter needed for search field

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#543]
When finding an object via the main page search field (left top side), and after typing text, a DOUBLE enter (2 times) must be pressed before the search is activated. This should become only 1 enter.

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens ,

I can not reproduce this. Which browser (and version) do you use? Were the tests you did using an object which was already in the history of the browser? If so, it is possible that the browser first selects the object from the history when doing an 'enter' the first time. The second time is then used to search for the object.

**Comment by TomCorstjens** [comment]
i'm currently using Ms Edge as browser under windows v.10
It was a mix of existing and new objects, the issue is consistent.
Tom

----- Oorspronkelijk bericht -----
Van: Wim De Meester <notifications@github.com>
Aan: DeepskyLog/DeepskyLog <DeepskyLog@noreply.github.com>
Cc: TomCorstjens <tom.corstjens@telenet.be>
Verzonden: Mon, 04 Jan 2016 10:26:50 +0100 (CET)
Onderwerp: Re: [DeepskyLog] Double enter needed for search field (#543)

Hi @TomCorstjens ,

I can not reproduce this. Which browser (and version) do you use? Were the tests you did using an object which was already in the history of the browser? If so, it is possible that the browser first selects the object from the history when doing an 'enter' the first time. The second time is then used to search for the object.

---

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens,

I can only reproduce this in Edge when the object is already in the history. This is indeed the behavior of microsoft edge and we can not do anything about this issue...

**Comment by WimDeMeester** [comment]
Closing the issue as we can not fix it.
