### ISSUE TITLE
Steve Gottlieb data part II

### ISSUE THREAD

**Issue by rolfvandervleuten** [DeepskyLog/DeepskyLog#545]
I’ve attached my recent observations (183 NGCs and 42 ICs in the same format as previously sent) from Australia.  I checked Deepskylog and a large percentage of these have no current observations.

The observations were made at Markdale Homestead, a working sheep farm outside of Crookwell, NSW at -34.2350829° latitude,149.2981888 longitude.  It was quite dark — SQM readings were consistently 21.8-21.9, reaching 22.0 on occasion.

I observed with two scopes; a 30-inch f/4.5 SDM Dobsonian and a 25-inch f/5 Obsession.  I used a Paracorr with the 30-inch, but not the 25-inch.  There were mainly two eyepieces used, a 13mm Ethos, which yielded 303x in the 30-inch and 244x in the 25-inch, and a 10mm Ethos, which yielded 394x in the 30-inch and 318x in the 25-inch.
[NGCs.txt](https://github.com/DeepskyLog/DeepskyLog/files/78184/NGCs.txt)
[ICs.txt](https://github.com/DeepskyLog/DeepskyLog/files/78186/ICs.txt)

**Comment by WimDeMeester** [comment]
Add the observations to DeepskyLog.
