### ISSUE TITLE
Scrolling with "TAB" key does not allow open drop-down menu with arrow key

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#558]
When recording a "new observation" and you scroll through the observation-form via the TAB cursor, you cannot open a drop-down window with the arrow-down key on your keypad.

**Comment by TomCorstjens** [comment]
when pushing the arrow-down button, the entire screen goes down instead opening the drop-down menu (e.g. eyepiece, filter, etc.)

**Comment by WimDeMeester** [comment]
It looks like the new way to do this, is to press 'Enter' first. Pressing 'Enter' will open the drop-down menu. After that you can select the entries using the arraow keys. I'm investigating how to change this.

**Comment by WimDeMeester** [comment]
Problem and possible solution described in https://github.com/select2/select2/issues/3472 
Patched the select2 library we use in DeepskyLog. Should be solved now.
