### ISSUE TITLE
Error when #List with overview of observers

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#559]
When clicking on the number list details in the Observers overview:
![waarnemers_listm](https://cloud.githubusercontent.com/assets/12647470/12356609/d39eb03c-bba3-11e5-923b-4d0a2a96f472.PNG)

This gives an error message: 
![waarnemers_list_mbug](https://cloud.githubusercontent.com/assets/12647470/12356600/c88655c4-bba3-11e5-84ec-67b8bd314e8a.PNG)

MAJOR bug because this is an important functionality to manage observation lists.

**Comment by WimDeMeester** [comment]
Small typo in the URL. The username was not added. Easy to fix.
