### ISSUE TITLE
Confusing "M45" prefill in Search field

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#560]
Urania workshop: Multiple users found it confusing that M45 was prefilled in the search field. 
![m45_prefill](https://cloud.githubusercontent.com/assets/12647470/12359702/3c29eb20-bbb4-11e5-8b6e-4b2cac9ff2f8.PNG)
Better to remove M45 prefill  or change it to "search" or "enter here"

**Comment by WimDeMeester** [comment]
Change M 45 to 'Enter object name'.
