### ISSUE TITLE
Main "Search observation" button gives Error message

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#561]
Main screen -> fill in value in the search field (e.g. M56) and press the "search observation" button. 
-> this gives an error message : 
![error_searchobs](https://cloud.githubusercontent.com/assets/12647470/12359834/b4405a5e-bbb4-11e5-9886-3b89d168cbd1.png)
Important bug, this is a default functionality. 
When clicking the error message away, it seeks the data-tables continues to be loading: 
![error_searchobs2](https://cloud.githubusercontent.com/assets/12647470/12359930/38ceb388-bbb5-11e5-8296-48572d18387f.png)

**Comment by WimDeMeester** [comment]
For some objects, we do indeed see this error (e.g. M 56). Other objects (like M 45) do not show this error...

**Comment by WimDeMeester** [comment]
There was an error in the database for 12 objects. M 56 is one of them. Well spotted! I corrected the database entry and adapted the code so that the error will no longer occur when the database should have the same problem...
