### ISSUE TITLE
Unclear usability: double entry area for search observations

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#563]
Urania Workshop feedback: 
For a new user (not familiar with DSL) that uses the "search query" for finding observations

= Not clear where to enter the deepsky object: either on left side, either in middle: 

![search_double_usability](https://cloud.githubusercontent.com/assets/12647470/12360179/9eef4dca-bbb6-11e5-9063-5286d1ac0c93.PNG)

SUGGESTED to hide the left panel so only the query area is visible. Improvement of usability!

**Comment by WimDeMeester** [comment]
I don't think that removing the left panel will make the usability better. Because, sometimes seeing the left panel and sometimes not will only add confusing. I will change the title from 'Search' to 'Quick Search' now. We can still discuss how to go further with this issue...

**Comment by TomCorstjens** [comment]
This indeed is a matter of decision making. Suggest to put this on agenda of next DSL developers meeting.
Quick fix is already an improvement.

**Comment by TomCorstjens** [comment]
Both functions are valuable. The label "quick search" is a fine fix. Issue solved.
