### ISSUE TITLE
Forgotten translation "stored queries" at botton search query menu

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#564]
Workshop Urania: 

In the query area for finding an observation, totally at the bottom there is the possibility to store a query. 
Usability feedback: 

1. not all were IT familiar and did not know what a "query" is ... :-)))

2. The section and buttons are not translated into DUTCH (text, buttons, etc.)
![querylanguage](https://cloud.githubusercontent.com/assets/12647470/12360317/8ece4968-bbb7-11e5-9e41-94a988f39701.png)

**Comment by WimDeMeester** [comment]
Change to 'Stored searches' in English, translated in Dutch. Apparently, the 'Save As...' button does not work. Also fixing this.

**Comment by WimDeMeester** [comment]
The 'Save As..' button did not work for the observations. Difficult to find the problem, but easy fix once found.
