### ISSUE TITLE
Unclear / usability: Split entry of catalogue and number 

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#565]
URANIA Workshop: many users were confused and did not found it clear / user friendly how object details (OBJECT NAAM) must be entered when query for an object or an observations: 
1. Some did enter "M57" whereas only "M" -> no results
![entry_usability](https://cloud.githubusercontent.com/assets/12647470/12360420/37285b58-bbb8-11e5-8b35-24a917278765.png)

2. Unlogic that the numeric value field is BELOW the catalogue field. Were searching at the right side for that field...

**Comment by WimDeMeester** [comment]
I see two possible solutions here:
+ Remove the catalog name drop-down altogether.
+ Show the drop down with the catalog names and the number next to each other. Show 'Select catalog' and 'Select object in catalog' as a hint what to do.

I prefer option 2. What do you think @TomCorstjens ?

**Comment by TomCorstjens** [comment]
Also prefer option #2

**Comment by WimDeMeester** [comment]
Implemented option 2.
