### ISSUE TITLE
Dropdown_SuggestedValues hides buttons

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#566]
URANIA workshop: 

When a user searches an object (main screen - left side) and already had searched other similar objects, there appears a drop-down with suggested values. 
--> This functionality hides the buttons !!! not user friendly. e.g in picture below: what to do (panic!) if I really want to search only NGC7 ==> buttons have disappeared. 

SUGGESTED that there is 
- either no drop-down (or no cache)
- either the drop-down appears on right side of the field, so buttons remain visible.

![dropdown](https://cloud.githubusercontent.com/assets/12647470/12360608/4067a8da-bbb9-11e5-962b-b2beb60b1e2e.PNG)

**Comment by WimDeMeester** [comment]
This is really something that we can not change. This is the cache of the browser, and has nothing to do with DeepskyLog. Closing the issue.
