### ISSUE TITLE
Buttons at Right side: not user-friendly

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#568]
WORKSHOP  URANIA: 

Not user friendly that many type of "enter" confirmation buttons are displayed at the right side of the screen, whereas majority of entry fields are on (natural) left side. 

PROPOSAL: The screen display of data confirmation buttons should always been at the left side of the screen. 

![buttons_right](https://cloud.githubusercontent.com/assets/12647470/12361157/cc7c8798-bbbc-11e5-9555-91c27f597a93.png)

**Comment by TomCorstjens** [comment]
With a large entry field, also the button remains on top / bottom and is NOT VISIBLE.
SOLUTION: the button must be fixed and always visible (not scrolling outside the screen)

**Comment by WimDeMeester** [comment]
The current layout does not make it possible to fix the buttons to the screen. I think that putting the buttons at the right side of the screen make them come out clearer. When they are at the left side, they disappear in the list of other buttons. 
What can / should be done is that the buttons are not only shown on top of the form, but also at the bottom. The observers will not need to scroll up again to click the button. 

If this solution is acceptable, can you give me a list of pages where this should be done?

**Comment by TomCorstjens** [comment]
Several users though gave feedback that they would prefer the button on the left side, and I agree with them. Like filling in a form, you move down in a linear way. At the end you expect also the button, at the left side.

**Comment by WimDeMeester** [comment]
What about the buttons at the top on the right and at the bottom on the left?

**Comment by WimDeMeester** [comment]
@TomCorstjens Is the current implementation better? If not, reopen this issue.

**Comment by TomCorstjens** [comment]
Yes, this is better. Logic at bottom left because that is the natural place, at end of recording, to also find the button.
