### ISSUE TITLE
"Add obs" button gives "new obs list" message when no observation location

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#572]
COMPLEX BUG : 

In case a user has not yet defined an observing location 
AND this user wants to log a new observation (no location can be selected): 

![_bug1](https://cloud.githubusercontent.com/assets/12647470/12361881/fe6f26bc-bbc0-11e5-93af-595623b53dc1.png)

--> User enters some logic information (e.g. date, observation details) but cannot select an observation location, 

--> And then clicks the button "add observation" at the TOP (!!) of the screen: 

BUG 1: a message appears that the mandatory fields must be entered, it is not identified / clear which fields are really mandatory (==> they should be highlighted, e.g. in red)

BUG 2: a value of -1 appears in the SQM field (???) 

![_bug2](https://cloud.githubusercontent.com/assets/12647470/12361891/084737b0-bbc1-11e5-884b-536499f3af89.png)

BUG 3: When the user clicks the button "add observation" at the BOTTOM (!!) of the screen:
A very unlogical screen appears: 
![_bug3](https://cloud.githubusercontent.com/assets/12647470/12361966/6a305164-bbc1-11e5-892e-54a85ea5ecae.png)

**Comment by WimDeMeester** [comment]
Bug 1 solved by setting the required keyword in the select html tag. This will point to the fields that should be filled out.

**Comment by WimDeMeester** [comment]
Bug 2 fixed.

**Comment by WimDeMeester** [comment]
I can not reproduce bug 3. Can you try to reproduce the bug again @TomCorstjens ? And describe in more detail how I can reproduce the bug?

**Comment by WimDeMeester** [comment]
@TomCorstjens If you can reproduce part 3 of the bug, please describe how to do this and reopen this issue.

**Comment by TomCorstjens** [comment]
1. Login as "urania1" (this has not yet a location defined)
2. click button "new observation"
3. Enter any text for the observation
4. click on the BOTTOM RIGHT BUTTON (not the top one)
then the error message appears - I just reproduced it again.

**Comment by WimDeMeester** [comment]
The version of deepskylog on the testversion was not the latest version. Can you try again?

**Comment by TomCorstjens** [comment]
Tried again and now it is different: it gives the message "select object from the list"
BUT 
1). not clear what list an object must be selected from
2). There is nothing in the "location" list. Hence the error message is incorrect and should state "there is nothing you your list - please first define content (an observation location)" or something like that.

**Comment by WimDeMeester** [comment]
The location was always mandatory. It will also break compatibility with OAL when the location would not be mandatory. The location will stay mandatory. If the observers do not want to add a location, they can still make a fake location. 

1) The message is shown exactly at the location where the list is on the screen. If the list is not visible (because you have to scroll up), the message is at the top of the window. 

2) The error message can not be changed, as this is functionality provided by the browser. Different browsers will give different messages.

**Comment by TomCorstjens** [comment]
Okay, Clear. Issue can be closed. 

----- Oorspronkelijk bericht -----

Van: "Wim De Meester" <notifications@github.com> 
Aan: "DeepskyLog/DeepskyLog" <DeepskyLog@noreply.github.com> 
Cc: "TomCorstjens" <tom.corstjens@telenet.be> 
Verzonden: Vrijdag 22 januari 2016 10:20:56 
Onderwerp: Re: [DeepskyLog] "Add obs" button gives "new obs list" message when no observation location (#572) 



The location was always mandatory. It will also break compatibility with OAL when the location would not be mandatory. The location will stay mandatory. If the observers do not want to add a location, they can still make a fake location. 

1) The message is shown exactly at the location where the list is on the screen. If the list is not visible (because you have to scroll up), the message is at the top of the window. 

2) The error message can not be changed, as this is functionality provided by the browser. Different browsers will give different messages.
