### ISSUE TITLE
NEW button logo incorrectly used for logging new observation

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#573]
URANIA WORKSHOP: 

The (new) button on the main screen is not clearly defined, because many new users believed this button is to log a new observation. 

![new](https://cloud.githubusercontent.com/assets/12647470/12362372/3c8cdaf0-bbc3-11e5-881d-a7b3653089a9.PNG)

SUGGESTED TO RENAME : "Latest observations" instead of new observations...

**Comment by WimDeMeester** [comment]
Changed title to 'Latest observations'

**Comment by WimDeMeester** [comment]
When you can provide me with another icon / button, please do so.

**Comment by TomCorstjens** [comment]
The icon is quite ok, else it becomes too heavy. Change of text with icon is good fix. 

----- Oorspronkelijk bericht -----

Van: "Wim De Meester" <notifications@github.com> 
Aan: "DeepskyLog/DeepskyLog" <DeepskyLog@noreply.github.com> 
Cc: "TomCorstjens" <tom.corstjens@telenet.be> 
Verzonden: Maandag 18 januari 2016 03:27:42 
Onderwerp: Re: [DeepskyLog] NEW button logo incorrectly used for logging new observation (#573) 



When you can provide me with another icon / button, please do so.
