### ISSUE TITLE
BUG: URL to "new location" in personal settings does not work

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#574]
In the personal settings page: 
The URL link "nieuwe plaats"  to generate a new observing location, does not work. 

![url_location](https://cloud.githubusercontent.com/assets/12647470/12362583/61152fe8-bbc4-11e5-9d35-98c025fa1d34.png)

**Comment by WimDeMeester** [comment]
Was already fixed in DeepskyLog 5.0.30. Wrong link was used.
