### ISSUE TITLE
Observer counts last year observations set on "zero"

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#609]
When consulting the overview of most active observers, there is an apparent bug in the values for observations and sketches of last year.

Example: I'm very sure that Tom Borger has made a large amount of logs over the past 12 months, but his statistics display "zero". My statistics seem to be OK.

![dslbug](https://cloud.githubusercontent.com/assets/12647470/14310380/d9aa161e-fbe1-11e5-80c4-a9474d98cb36.PNG)

**Comment by WimDeMeester** [comment]
That was a problem in the database. Some of his observations where entered in the database as 'tom borger'. I corrected this to 'Tom Borger'. This fixes the problem.
