### ISSUE TITLE
Error message after deleting an observation

### ISSUE THREAD

**Issue by LindaPlaterink** [DeepskyLog/DeepskyLog#611]
I found that I had one observation double in the list of my observations. Therefore I opened the details on one of them and selected the delete-button.  When choosing the page-back button in the browser (google chrome), I got this error message: 

DeepskyLog encountered a problem. Could you please report it to the Developers?

Report problem with error message: No observed object found in view_observation.php

You can report the problem by sending an email to developers@deepskylog.be.

Thank you.

**Comment by WimDeMeester** [comment]
It is normal that an error is thrown. When you click the page-back button, you return to the page with the details of the observation. However, this observation is deleted now, hence the error. I will make sure that the error is not fatal anymore and that the link to send an email to the developers is not longer visible.
