### ISSUE TITLE
Error message about timezone when opening a link to DSL

### ISSUE THREAD

**Issue by LindaPlaterink** [DeepskyLog/DeepskyLog#612]
A person on the astrofum sent me this linke: http://www.deepskylog.be/index.php?indexAction=detail_observation&observation=45399&dalm=AO

When I opened it, I got the following error message:

DeepskyLog encountered a problem. Could you please report it to the Developers?

Report problem with error message: DateTimeZone::__construct(): Unknown or bad timezone ()

You can report the problem by sending an email to developers@deepskylog.be.

Thank you.

The linked page displayed normally.

**Comment by WimDeMeester** [comment]
Probably a problem in the database. I will check it.

**Comment by WimDeMeester** [comment]
There were indeed some problems in the database. Some of the observations had locationid=0. This should never be possible. Was this a problem with the cvs import or the oal import?
