### ISSUE TITLE
Text in session has been cut off

### ISSUE THREAD

**Issue by LindaPlaterink** [DeepskyLog/DeepskyLog#618]
Last night I created a new observing session. In the comment field, I wrote my text and saved it. This morning it was cut off to:
"First light C8. Het collimeren vooraf gaf een redelijk resultaat. Maar is wel gedoe.
Mars stond erg laag en was gewoon niet scherp te krijgen. Saturnus nog even tussen de bomen. Jupiter stond in het westen en heb ik niet bekeken, vanwege geen zicht in die richting.
Daarna de ringnevel bekeken. Hij was wel redelijk makkelijk te vinden, ondanks dat het heel licht was. Geen contrast met de hemelachtergrond.
Daarna epsilon 2 Lyrae gescheiden met 12,5mm ortho. Een nauwe dubbelster. De epsilon 1 wa"

I did write a bit more after that last sentence and the text looked normal when I saved it.
If there is a maximum number of characters that can be stored in the field, then please make the field equally small when entering text.

**Comment by WimDeMeester** [comment]
the maximum number of characters was 500. I raised this to 5000 and will make sure that field only allows 5000 characters.

**Comment by WimDeMeester** [comment]
![screen shot 2016-05-27 at 15 06 26](https://cloud.githubusercontent.com/assets/7261529/15608906/0b3f5b2c-241d-11e6-8c30-f7fe2faf1741.png)
