### ISSUE TITLE
Size of new objects in decimal arcseconds not possible

### ISSUE THREAD

**Issue by BobHogeveen** [DeepskyLog/DeepskyLog#628]
When entering a new object, especially a double star, size can only be given in full arcseconds.
For close doubles this is inconvienent because there is a large difference between, e.g., 0,6", 1" and 1,4", where in all cases 1" can only be entered.

**Comment by TomCorstjens** [comment]
The decimal sign should be entered with a **point** - not a comma. 
Then it works fine.

**Comment by BobHogeveen** [comment]
Sorry, but this does not work for "normal" users. When entering e.g. 8.5 a message appears which says that the entry is not correct and should be a full number.
It does work with administrator rights (which I have myself).
So not a big problem for me, but it may be usefull for other users
