### ISSUE TITLE
Simeis catalogue not accurate, instead are Sharpless objects

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#634]
There are quite some objects in the Simeis cataloque that are not correct and the number belongs to the Sharpley catalogue.  Example: Simeis 308 : Sh2-308 

The total list of 50 Simeis objects in DSL must be reviewed and corrected where needed. 
(and only a very few Simeis objects are even visible ...)

**Comment by TomCorstjens** [comment]
I'll work on an **update** and **correction** of the Simeis list -> file shall be added to this ISSUE

**Comment by TomCorstjens** [comment]
[Simeis list.xlsx](https://github.com/DeepskyLog/DeepskyLog/files/684767/Simeis.list.xlsx)

Attached is the reviewed file of **Simeis Objects**. 
(1) Many are duplicates of Sharpless objects => action: **remove** the Simeis entries from database
(2) Remaining items are incorrect => action: **correct** to the identified Catalogues reference (most of time "Sh 2-xxx)

Also popular names were added, for completion.

**Comment by TomCorstjens** [comment]
reference for work: http://galaxymap.org/cat/list/sharpless/1

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens , what is the status of this ticket?

**Comment by TomCorstjens** [comment]
Nothing done. Awaiting help or instructions from Eric, on adapting the database.Ecxel file is ready to convert Simeis into Sharpley id's.

Sent from my Samsung S6 edge
-------- Oorspronkelijk bericht --------Van: Wim De Meester <notifications@github.com> Datum: 16/02/17  11:25  (GMT+01:00) Aan: DeepskyLog/DeepskyLog <DeepskyLog@noreply.github.com> Cc: TomCorstjens <tom.corstjens@telenet.be>, Mention <mention@noreply.github.com> Onderwerp: Re: [DeepskyLog/DeepskyLog] Simeis catalogue not accurate, instead are Sharpley objects (#634) 
Hi @TomCorstjens , what is the status of this ticket?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeepskyLog/DeepskyLog","title":"DeepskyLog/DeepskyLog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeepskyLog/DeepskyLog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@WimDeMeester in #634: Hi @TomCorstjens , what is the status of this ticket?"}],"action":{"name":"View Issue","url":"https://github.com/DeepskyLog/DeepskyLog/issues/634#issuecomment-280292628"}}}

**Comment by WimDeMeester** [comment]
I will see if I can give you the correct information on of the next days...

**Comment by WimDeMeester** [comment]
I think that you can find the needed information in  https://github.com/DeepskyLog/DeepskyLog/wiki/Managing-objects-using-CSV-files

You need to create a file with the following structure. I give an example for the first line:

NN;Simeis 101;Sh;2-101
AN;Simeis 101;;Tulip Nebula
RA;Simeis 101;;20.0

I'm sure it is possible to create this list directly out of your excel file... If needed, I can investigate it a bit.

**Comment by TomCorstjens** [comment]
Very useful. Think that first all Sh objects must be made with NOC code and then move all existing observations under the new code by RRO code.I'll prepare the csv file. But need help to upload this, have not done this in the past an I do not want to mess up the database ;)


Sent from my Samsung S6 edge
-------- Oorspronkelijk bericht --------Van: Wim De Meester <notifications@github.com> Datum: 16/02/17  16:39  (GMT+01:00) Aan: DeepskyLog/DeepskyLog <DeepskyLog@noreply.github.com> Cc: TomCorstjens <tom.corstjens@telenet.be>, Mention <mention@noreply.github.com> Onderwerp: Re: [DeepskyLog/DeepskyLog] Simeis catalogue not accurate, instead are Sharpley objects (#634) 
I think that you can find the needed information in  https://github.com/DeepskyLog/DeepskyLog/wiki/Managing-objects-using-CSV-files
You need to create a file with the following structure. I give an example for the first line:
NN;Simeis 101;Sh;2-101

AN;Simeis 101;;Tulip Nebula

RA;Simeis 101;;20.0
I'm sure it is possible to create this list directly out of your excel file... If needed, I can investigate it a bit.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeepskyLog/DeepskyLog","title":"DeepskyLog/DeepskyLog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeepskyLog/DeepskyLog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@WimDeMeester in #634: I think that you can find the needed information in  https://github.com/DeepskyLog/DeepskyLog/wiki/Managing-objects-using-CSV-files\r\n\r\nYou need to create a file with the following structure. I give an example for the first line:\r\n\r\nNN;Simeis 101;Sh;2-101\r\nAN;Simeis 101;;Tulip Nebula\r\nRA;Simeis 101;;20.0\r\n\r\nI'm sure it is possible to create this list directly out of your excel file... If needed, I can investigate it a bit."}],"action":{"name":"View Issue","url":"https://github.com/DeepskyLog/DeepskyLog/issues/634#issuecomment-280365708"}}}

**Comment by WimDeMeester** [comment]
That is indeed a better option. I will make a copy of the current database and put it on the test server. There, you can make all tests needed.

**Comment by TomCorstjens** [comment]
Do you have a tutorial how to upload such a csv file? 
I'll first experiment op the test server, good learning experience.
Oh and by the way: I'm extending the exercise to upload all (!!) 313 Sharpless objects into deepskylog. That this catalogue is also complete.

**Comment by WimDeMeester** [comment]
I have made a small movie on how to upload such a CSV file. You can find it [here](https://github.com/DeepskyLog/Documents/blob/master/HowTos/Manage%20objects%20using%20CSV%20file.mp4?raw=true)

**Comment by TomCorstjens** [comment]
Large database work completed : all Sharpless objects are uploaded and related Simeis objects are removed. 

See excel file for raw data: 
[Simeis list.xlsx](https://github.com/DeepskyLog/DeepskyLog/files/784093/Simeis.list.xlsx)

Issue closed !!!
