### ISSUE TITLE
Managing CSV files: DESC code is not described in the github wiki

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#639]
In order to adapt the description of an object, the code DESC can be used

Please add the algoritm what arguments should be included, into the DSL github wiki

**Comment by WimDeMeester** [comment]
Can you show me an example how to use it? Or can you adapt the wiki yourself?

**Comment by TomCorstjens** [comment]
The way it works: 
DESC - Object - [empty] - description text

For example: 
DESC;NGC 1;;NumberOneGalaxy

I've tried to adapt the wiki but I did not found how to do this.

**Comment by WimDeMeester** [comment]
Added to the wiki.
