### ISSUE TITLE
Messier 1 shows "Taki Star atlas" in exponential frequency

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#644]
See public lists: Tak Star Atlas appears very very often: 

![image](https://cloud.githubusercontent.com/assets/12647470/23321141/57bb37c6-fade-11e6-8fd5-4913e2cb0062.png)

**Comment by WimDeMeester** [comment]
This is a problem in the database. Should be fixed.

**Comment by WimDeMeester** [comment]
Fixed in the database. M 1 was 30 times in the Taki list...
