### ISSUE TITLE
Prohibit to define new "Catalogi"

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#645]
Currently I'm cleaning up all the unwanted or erroneous catalogi see issue #429 
This is a massive job and will require weeks of work. 

Strong request to maintain afterwards the list of CATALOGI by the administrators and prohibit that users can define their own catalogi (and jeopardise all work currently done) 

SOLUTION: 
When entering a new object, a regular user should only be able SELECTING an existing catalogue. 
In case their reference does not appear: send email to admin or enter it as regular number (e.g. 42 Ori) to avoid explosion of catalogi again. 

Thank you.

**Comment by RemRanger** [comment]
It appears catalogs may be created without the user intending to. For instance, "42 Ori" was entered intending to add the binary star under that name, without a catalog. DSL, however, turned out to actually create a catalog named "42".

**Comment by TomCorstjens** [comment]
Indeed. The interface does not work optimal.
Best solution is to block creation of new catalogues and only enable that action by admin. Users shouls only be able:- add new object to existing catalogue- create named objects that are not catalogue related.- give alternative name to existing object, BUT with same rules as above.


-------- Oorspronkelijk bericht --------Van: RemRanger <notifications@github.com> Datum: 9/03/17  08:53  (GMT+01:00) Aan: DeepskyLog/DeepskyLog <DeepskyLog@noreply.github.com> Cc: TomCorstjens <tom.corstjens@telenet.be>, Author <author@noreply.github.com> Onderwerp: Re: [DeepskyLog/DeepskyLog] Prohibit to define new "Catalogi" (#645) 
It appears catalogs may be created without the user intending to. For instance, "42 Ori" was entered intending to add the binary star under that name, without a catalog. DSL, however, turned out to actually create a catalog named "42".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeepskyLog/DeepskyLog","title":"DeepskyLog/DeepskyLog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeepskyLog/DeepskyLog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@RemRanger in #645: It appears catalogs may be created without the user intending to. For instance, \"42 Ori\" was entered intending to add the binary star under that name, without a catalog. DSL, however, turned out to actually create a catalog named \"42\"."}],"action":{"name":"View Issue","url":"https://github.com/DeepskyLog/DeepskyLog/issues/645#issuecomment-285280069"}}}

**Comment by TomCorstjens** [comment]
Issue appears solved when attempting to add a new object: 

![image](https://user-images.githubusercontent.com/12647470/49402135-5ecd8280-f749-11e8-9352-ece73f47d3ca.png)
