### ISSUE TITLE
Create Skysafari list directly from Deepskylog

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#646]
See link: 
http://www.astroforum.nl/forum/visueel-waarnemen/schetsen/1328007-onontbeerlijk?p=1328141#post1328141

Transpose a CSV file from Deepsklog into a skysafari list:
Website: http://remranger.com/skylist/

Rem want to help in creating code to enable direct creation of observation lists into SkySafari.

**Comment by WimDeMeester** [comment]
Good news! You can always invite Rem to GitHub and Slack if you want to.

**Comment by RemRanger** [comment]
Hi guys, i just created a GitHub account. Trying to find my way now.

**Comment by WimDeMeester** [comment]
Hi @RemRanger , I have invited you to the DeepskyLog Developers team on GitHub. If you send me a mail (deepskywim@gmail.com) with your email address, I can give you access to Slack (a chat-like application, where we can easily discuss things about the deepskyLog development).
