### ISSUE TITLE
Object Type "Double Star" appears 2 times in menu "selection"

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#652]

**Comment by TomCorstjens** [comment]
When searching for objects though advanced query: 

![image](https://cloud.githubusercontent.com/assets/12647470/24063105/9282a426-0b5e-11e7-9dc2-fc1c1b242b0b.png)

**Comment by TomCorstjens** [comment]
Reason: For the same object type, two database codes exist: 

![image](https://cloud.githubusercontent.com/assets/12647470/24063143/b9da9b8c-0b5e-11e7-8107-17e49e93ae65.png)

Any suggestion how we can harmonise this into ONE TYPE ?

**Comment by WimDeMeester** [comment]
I will move all objects with the AA2STAR type to DS in the database. This means that to add a new object, you also need to use the DS type.
