### ISSUE TITLE
Code TYP for catabase change CSV file fails --> wrong WIKI

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#653]
When changing an _existing object type_ to another object type via code TYP, the result becomes blank. 

Example: Alessi-Teutsch catalogue had 8 objects as ASTER code but this was wrong as all are OPNCL type. 
When using script e.g. << TYP; Alessi-Teutsch 6;OPNCL >>
All values at Type are emptied without corrected value

![image](https://cloud.githubusercontent.com/assets/12647470/24072547/2b18ee68-0be9-11e7-99c7-790b1eb3862d.png)

How can this be corrected?

**Comment by TomCorstjens** [comment]
Applicable for 8 objects:
![image](https://cloud.githubusercontent.com/assets/12647470/24072576/83a76f82-0be9-11e7-9317-1f9358071b90.png)

**Comment by TomCorstjens** [comment]
Current situation:

![image](https://cloud.githubusercontent.com/assets/12647470/24072610/f4570c4c-0be9-11e7-8aa7-630b23f3ccf5.png)

**Comment by TomCorstjens** [comment]
Via experimentation: problem solved. 
There is a need to extra empty field in CSV file

![image](https://cloud.githubusercontent.com/assets/12647470/24075075/2bfe5e04-0c15-11e7-89fb-15da70e28d4a.png)

Then it works fine. 

**CONCLUSION: The Wiki query is wrong !!!** 

Silimar for e.g. D1 correction: an extra space is needed; the wiki is wrong. 

@WimDeMeester : please correct the wiki to avoid this problem in future.

**Comment by WimDeMeester** [comment]
Fixed in the wiki. I think you could also change the wiki page. That's what the wiki is for ;-)
