### ISSUE TITLE
Catalogi drop-down box too small

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#654]
When "Overview" -> Catalogi 

Then a screen appears whith a rather small drop-down box. 
For one catalogus (Alessi-Teutsch) this does not display in one line. 

![image](https://cloud.githubusercontent.com/assets/12647470/24073823/2cc977c2-0bfe-11e7-90e3-6cce99172ff2.png)

Request: enlarge the drop-down box slightly to ensure all catalogi fit on one line.

**Comment by WimDeMeester** [comment]
Fixed in DeepskyLog 5.0.51. The whole width of the screen is now taken for the drop-down box.
