### ISSUE TITLE
Error & fail to update profile picture

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#702]
![dslissue](https://user-images.githubusercontent.com/12647470/36811002-ac8efe48-1ccc-11e8-8d9a-a483b7ec5c0f.png)
Following error message appears when update of profile picture. 
Browser used: Microsoft Edge

EXTRA: 
When using Firefox, the error message does not appear, but the updated jpg file is not processed (actual picture remains the same)

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens 

There is indeed a problem when using microsoft browsers... I have updated the external library that handles the upload of images, so can you try again?

In firefox, the change was successful, but you should force reload the page (Shift + Reload button).

**Comment by TomCorstjens** [comment]
Yes it works - but only after 3x refresh window via F5 button.

**Comment by TomCorstjens** [comment]
I've tested this one today using my admin account and … both in Edge and Firefox the profile pic does not upload.

**Comment by WimDeMeester** [comment]
Works in the upcoming laravel version of DeepskyLog. Will not fix this for the old version.
