### ISSUE TITLE
Problem with uploading observations in .csv format

### ISSUE THREAD

**Issue by VedranVrhovac** [DeepskyLog/DeepskyLog#705]
Hi, 
I have problem with uploading observations in .csv files. My files get rejected, with Deepskylog reporting that date is from future (which is not), objects are not in databases or etc...
At first, csv file upload was working ok and most of my observations were uploaded that way. After encountering problems, I've tried different browsers (Firefox and Chrome), creating new files, new observations. I have even download already uploaded observations in .csv format and tried them to upload again without success. In the end, I've used generic template from "Import observations from a CSV file" page and that got rejected to. 
These problems were experienced on two separate computers, both running Windows 10 Home, 64 bit operating system.

To help detect problem, I have attached is .csv file (in zip format) with which I have problems.
[2017-10-15.zip](https://github.com/DeepskyLog/DeepskyLog/files/1780523/2017-10-15.zip)

Thanks,
Vedran

**Comment by WimDeMeester** [comment]
Can you try again? I changed a little thing. Can you tell me which deepskylog domain you are using? Is it deepskylog.org?

**Comment by VedranVrhovac** [comment]
Hi,
I've managed to upload observations now :) 👍 
I am using http://www.deepskylog.org domain.

Thanks, 
Vedran

**Comment by WimDeMeester** [comment]
Thanks for letting me know!
