### ISSUE TITLE
H400 and Messier counts missing 

### ISSUE THREAD

**Issue by janbstar** [DeepskyLog/DeepskyLog#728]
Details info window: H400 and Messier Caldwell etc counts are missing
This happened around 2 weeks ago
Desktop, Windows 10, IE or Firefox
![dsl_details](https://user-images.githubusercontent.com/40757866/42155307-527e5020-7de8-11e8-9e59-f94a0e838aa6.jpg)

**Comment by WimDeMeester** [comment]
Was indeed a small bug. It should be fixed now.
