### ISSUE TITLE
Adding new observing location: Google maps crashes when scrolling

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#730]
When adding a new observing location, and typing the location, 
-> google maps shows the location. Zooming out + in works OK
But when you want to move the map, it crashes and becomes a white screen. 
Note: Issue using Browser "Edge"

**Comment by WimDeMeester** [comment]
I'm in the process of reworking the add observation page. I'll let you know when a version that can be tested is available. Do you have the same problem with other browsers?

**Comment by TomCorstjens** [comment]
Not tested yet with other browsers. 


Van: "Wim De Meester" <notifications@github.com> 
Aan: "DeepskyLog/DeepskyLog" <DeepskyLog@noreply.github.com> 
Cc: "TomCorstjens" <tom.corstjens@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Donderdag 6 september 2018 09:07:41 
Onderwerp: Re: [DeepskyLog/DeepskyLog] Adding new observing location: Google maps crashes when scrolling (#730) 



I'm in the process of reworking the add observation page. I'll let you know when a version that can be tested is available. Do you have the same problem with other browsers?

**Comment by TomCorstjens** [comment]
Tested in Firefox - it works fine there

**Comment by WimDeMeester** [comment]
I tested this today in Edge, but I don't see this problem. Which version of Edge do you use? You can check it if you click 'Settings' in the menu '...' at the right. I tested it on Edge version 42.17134.1.0 and EdgeHTML 17.17134.

**Comment by WimDeMeester** [comment]
Problem solved in the new version 2018.9 to be released shortly.
