### ISSUE TITLE
Adding a location does not work at all

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#731]
**Describe the bug**
Adding a new location doesn't work anymore. The system does nothing when you press the blue 'Zoek locatie' button after entering a city name (Fourdrain, France). When you enter the name of the location  in field 2 and press the green"Voeg locatie toe" button, there is a warning box about entering all the fields. If you then make op typical values of NELM and SQM  and enter these, the system still complains about all required files not being added. You also get the list of locations.

**To Reproduce**

1. Choose Toevoegen > Waarneemplaatsen
2. Enter the name of the new location in box 1 above the Google maps
3. Enter you choose name
4. Skip NELM nad SQM as you do not know them

**Expected behavior**
A new waarneemlocation is added.

**Screenshots**

**Desktop (please complete the following information):**
 - Mac OS 10.13.6
 - Safari
 - Version 1.11.2

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iOS 11
 - Browser Safara
 - Version: unknown

**Comment by WimDeMeester** [comment]
Do you see the google map? Is the map updated to the new location you entered in box 1?

**Comment by svdwal** [comment]
I don't see the map, no

**Comment by WimDeMeester** [comment]
I also use safari and I don't see the problems... Did you see this dialog? And did you click 'Alow'?

![image](https://user-images.githubusercontent.com/7261529/45475242-097e6800-b73c-11e8-9a43-021913f3dfda.png)

**Comment by WimDeMeester** [comment]
I think I understand the problem now... The " is probably causing the problem. I'll check later this week.

**Comment by WimDeMeester** [comment]
Problem is fixed in the new version that will be released shortly. I hope to set up a test server for the new release one of the following days.

**Comment by WimDeMeester** [comment]
I have put a test version online, where this problem should be fixed. Can you try at https://www.deepskylog.org/test/ ?
The database there is an old database, so don't be scared if you don't see your latest observations, locations, ...

**Comment by WimDeMeester** [comment]
I have fixed this in the new version. Can you try the test-version of DeepskyLog at https://www.deepskylog.org/test/
This site is using an old version of the database, so probably you have to play around a bit.

**Comment by svdwal** [comment]
It appears to work fine now. Choosing the campsite with the "" in the name is not a problem at all. Searching for a new site works too. Using "" in the seravh name is not a problem. Adding a name with "" is not a problem. Selecting it works fine too.

**Comment by WimDeMeester** [comment]
Thanks for testing this @svdwal !
