### ISSUE TITLE
Recent sketces display shows lates observations without sketch (FIREFOX)

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#736]
On the start page of deepskylog in FIREFOX - the "recent sketches" section makes link to latest observations without sketches. 

![image](https://user-images.githubusercontent.com/12647470/45926099-32aead80-bf1f-11e8-8384-1e076c380286.png)

**Comment by WimDeMeester** [comment]
Hi @TomCorstjens , is this only on the test server? In that case, the problem is that the link to the drawings is not made, so the behavior is expected.

**Comment by WimDeMeester** [comment]
Only on the test-server.
