### ISSUE TITLE
Searching for observations does not show not-found observations.

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#745]
**Describe the bug**
Searching for observations does not return not-found observations. This is at least inconvenient, as you want to know whether people made at least the attempt. 

**To Reproduce**
1. Enter UGCA39 in the search bix on the top left
2. Press 'Zoek waarnemingen'.
3. No observations are listed, while I have loggen a not-found observation.

**Expected behavior**
I would expect also to see not-found observations.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WimDeMeester** [comment]
Hi @svdwal 

There was a problem in the object database, that confused the DeepskyLog database query for UGCA 39. It should be solved now.
