### ISSUE TITLE
Sinds 18/10/2018: als ik "bekijk - mijn waarnemingen" klik zie ik een search query in chrome en explorer

### ISSUE THREAD

**Issue by patrickduis** [DeepskyLog/DeepskyLog#748]
als ik "bekijk - mijn waarnemingen" klik zie ik een search query in chrome en explorer.

Dit is wat ik dan zie in de browsers, volgens mij was dat gisteren (17-10-2018) nog niet zo:

(SELECT DISTINCT observations.id as observationid, observations.objectname as objectname, observations.date as observationdate, observations.description as observationdescription, observers.id as observerid, CONCAT(observers.firstname , ' ' , observers.name) as observername, CONCAT(observers.name , ' ' , observers.firstname) as observersortname, objects.con as objectconstellation, objects.type as objecttype, objects.mag as objectmagnitude, objects.subr as objectsurfacebrigthness, instruments.id as instrumentid, instruments.name as instrumentname, instruments.diameter as instrumentdiameter, CONCAT(10000+instruments.diameter,' mm ',instruments.name) as instrumentsort FROM observations JOIN instruments on observations.instrumentid=instruments.id JOIN objects on observations.objectname=objects.name JOIN locations on observations.locationid=locations.id JOIN objectnames on observations.objectname=objectnames.objectname JOIN observers on observations.observerid=observers.id WHERE observations.observerid = "patrickduis" ) ORDER BY observationid DESC;

**Comment by WimDeMeester** [comment]
Fixed. Thanks for the problem report!
