### ISSUE TITLE
Blank page after add new object

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#757]
**Describe the bug**
After manually adding an object (as normal user), DeepskyLog goes to a blank page.
It is remedied by refreshing the page, after which the newly added object is displayed.

**To Reproduce**
Follow procedure to manually add object.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: 63.0.3

**Comment by SkyNomad** [comment]
+ after refresh, a message appears that an object with that name (or alternative name) already exists, even though that's NOT the case.
It seems that the verification for double objects is misguided by the refresh, as the object was first added, and then DSL found it to be in the database.

**Comment by WimDeMeester** [comment]
This is indeed an error in DeepskyLog. The way the routing works in laravel will make it impossible for such errors to appear. Closing this issue as it will not be a problem in the laravel version of DeepskyLog.
