### ISSUE TITLE
Add Object resets list "Near Objects" in Object Details

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#758]
**Describe the bug**
When there are more than 10 objects around an object, the list "Near Objects" extends over multiple 'pages'. That's a good thing. But when an object is added from any page other than page 1, the list resets to page 1.

**Expected behavior**
To stay at the most recent page of the list (i.e. from where the object was added)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: 63.0.3 (64-bits)

**Comment by SkyNomad** [comment]
Also: length of displayed lines defaults back to 10
Also: sorting sequence defaults back to name

**Comment by WimDeMeester** [comment]
Sounds like an easy to solve problem, but it is not... I will need to think about it.

**Comment by WimDeMeester** [comment]
This problem does not appear anymore in the laravel version of DeepskyLog, where we use jquery Datatables for everything. Closing the issue.
