### ISSUE TITLE
buttons on lists: please put on top

### ISSUE THREAD

**Issue by SkyNomad** [DeepskyLog/DeepskyLog#759]
When scrolling through multiple pages of a list using the <<, <, >, >> etc buttons, these buttons constantly change place, as it is common for the list to change length (due to length of data vs. column width). It is annoying.
If these bottons would be placed on top, they would remain at their position.
It may also save screenplace, if buttons are placed in the same line as [kies kolommen]

**Comment by WimDeMeester** [comment]
Totally new system for tables in the laravel version. Closing it for the old version.
