### ISSUE TITLE
Moving column creates duplicate Colomn Menu

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#763]
**Describe the bug**
When moving a column on the screen, the dorp-down menu "choose column" is duplicated and all options appear double. 

**To Reproduce**
Step 1: go to any window with columns: 

![image](https://user-images.githubusercontent.com/12647470/49402819-4494a400-f74b-11e8-85ce-e139f74ce982.png)

Step 2: move any column (here: diameter one further to right) 
![image](https://user-images.githubusercontent.com/12647470/49402849-5f671880-f74b-11e8-9872-972db465ad20.png)

Step 3: click on button Choose column: 

![image](https://user-images.githubusercontent.com/12647470/49402890-80c80480-f74b-11e8-9ead-799203bb6b53.png)

**Expected behavior**
The choose column menu should 
- not duplicale
- change order in the menu (see #381 )

**Desktop (please complete the following information):**
Laptop + Edge v11

**Comment by WimDeMeester** [comment]
In the laravel version, we use jquery datatables. This solves this problem.
