### ISSUE TITLE
Deepsky Stars for Herschel400-II not working

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#764]
------- Oorspronkelijk bericht --------
Van: Torbjörn Holmqvist <torbjorn.s.holmqvist@spray.se> 
Datum: 28/12/18 22:18 (GMT+01:00) 
Aan: developers@deepskylog.be 
Onderwerp: Missing H400-II stars 

Hello,

My stars for observed Herschel 400-II objects have disappeared... I have observed 396 of them and have also investigated 2 non-existent/questionable objects.

Something must have happened....

Best regards and Happy New Year,

Torbjörn Holmqvist

**Comment by TomCorstjens** [comment]
**FEEDBACK GIVEN:** 

Hello Torbjörn, 
Yes - this is an (unexpected) effect due to a recent re-naming of the Herschel 400-II list in deepskylog. In the past this was named HII and confusing with general nebulae.
We'll check how to correct this on the "stars". Thank you for reporting this!!

**Comment by WimDeMeester** [comment]
Fixed in DeepskyLog 2019.1.
