### ISSUE TITLE
Add a night mode CSS

### ISSUE THREAD

**Issue by codecube** [DeepskyLog/DeepskyLog#766]
Hi DeepSkyLog, 
I do astronomical drawings and visual observation, and sometimes I have difficulties in logging my observation, I search the net and found you, but it's missing a Night Mode CSS, so that we could log our observations without loosing any of precious visual acuity.

I'm a former webdeveloper and webdesigner and if you want I believe I could help you guys implementing this feature.

Pedro Costa

**Comment by WimDeMeester** [comment]
Hi @codecube 

That would indeed be a very interesting addition! You really could be of help here. Thanks for proposing to implement this feature. 
If you are interested in running DeepskyLog locally on your development machine (for testing and developing), you can find more information here: https://github.com/DeepskyLog/Docker
Please do not hesitate to contact me if you have questions.

**Comment by WimDeMeester** [comment]
Hi @codecube 
Thanks for the progress! 

You can download the latest version of the DeepskyLog database (which includes your login) from http://www.ster.kuleuven.be/~wim/deepskylog.sql
Please let me know when you have downloaded the sql-dump, I will remove the file after that.
If you need instruction on how to use the latest version, just let me know.

I think it is a good plan to add the option in the user menu.

**Comment by codecube** [comment]
Hi @WimDeMeester I've just downloaded the dump. I'm not sure how should I load this database, I was thinking using an SQL client and use the address and credentials used by PHP.

**Comment by WimDeMeester** [comment]
Hi @codecube 

The best thing to do is to log in on your docker container and update the deepskylog database from there. You can do this the following way: 

1. Make sure to copy the deepskylog.sql file to the directory with the DeepskyLog source code

2. Find the id of the DeepskyLog docker container
`docker ps | grep deepskylog`

3. Log in to your running container
`docker exec -it <ENTER_YOUR_DOCKER_ID> /bin/bash`

4. Go to the directory with the DeepskyLog source code in the docker bash
`cd /var/www/html/`

5. Update the database
`mysql deepskylog < deepskylog.sql`

I hope this works.

**Comment by codecube** [comment]
It worked, but I'm having some problems with the session... I can login, but when I try to add an observation, I get the error "Report problem with error message: You need to be logged in to change your locations or equipment.".

**Comment by codecube** [comment]
I just added a pull request with feature.

**Comment by WimDeMeester** [comment]
> It worked, but I'm having some problems with the session... I can login, but when I try to add an observation, I get the error "Report problem with error message: You need to be logged in to change your locations or equipment.".

Did you find a solution for the login problem? 

I'll check the pull request later today.

**Comment by codecube** [comment]
I didn't solve it. 
It's probably related to my docker environment, the only php I touched was the head.php only to add a css class in some of the <link> tags, so I can assume that this is not a regression, or at least not introduced by me. Anyway, if you could test it a little bit for the pages that require authentication, it would be better.

**Comment by WimDeMeester** [comment]
I did the tests to add a new observation and it looks very good.  Check the comment in the pull request itself ;-)
I'll try to reproduce your login problem.

**Comment by WimDeMeester** [comment]
Thanks a lot for the pull request! I have just released the new version! You are always welcome to implement other things ;-)

**Comment by codecube** [comment]
Great!

Let’s discuss what are your priorities. I’m pretty confident that I can
help. What about responsive design?

**Comment by WimDeMeester** [comment]
Responsive design would be nice.  At this moment, DeepskyLog should already have some responsive design, but I'm sure that can be improved. We are still using bootstrap version 3, I guess bootstrap version 4 is already much better for responsive design.

My priorities are making it possible to add observations of non-deepsky objects possible in DeepskyLog (like planets, asteroids, satellites, ...) and rework the observation lists. 

But there are a lot of open issues were we should look into...

**Comment by codecube** [comment]
I understood today that is already responsive (if I shrink the web-browser window), but in iPhone, the responsive is not working.  I could have a look... 

I could also focus on your first priority.

Other subjects interesting could be the adoption and migration to a PHP MVC framework (I like symfony, but Codeigniter is simpler IMO), this could be key to maintain and add new features faster and have additional security.

Can we have other channel to discuss this? Do you have slack?

**Comment by WimDeMeester** [comment]
We have indeed slack.  I will add you ;-)
