### ISSUE TITLE
On iPad, the PDF observation forms cannot be downloaded properly

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#767]
**Describe the bug**
On the download page for the forms, 
https://www.deepskylog.be/index.php?indexAction=downloadForms, I cannot download the forms as PDF files. They are downloaded as some kind of text file.

**To Reproduce**
1. Go to 
https://www.deepskylog.be/index.php?indexAction=downloadForms
2. Scroll down to compact observation form
3. Press "Download" button
4. See the internal representation of the PDF file

**Expected behavior**
I would expect that the PDF file is downloaded as a PDF file, and is opened by Safari. As that is the common behaviour when downloading PDF files.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPad
 - OS: [e.g. iOS12

**Additional context**

**Comment by svdwal** [comment]
Changes are this is some missing application/pdf or whatever

**Comment by WimDeMeester** [comment]
There was a wrong configuration on the server. Fixed now.
