### ISSUE TITLE
Standard atlasses appear to be empty

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#768]
**Describe the bug**
The standard atlasses at 
https://www.deepskylog.be/index.php?indexAction=view_atlaspages are empty

**To Reproduce**
1. Go to 
https://www.deepskylog.be/index.php?indexAction=view_atlaspages
2. Select a size and orientation
3. Press Overview button
4. An atlas is now downloaded. However, it consist of a single white page. 
5. Opening it in iBooks shows the single emty page too.

**Expected behavior**
A pdf file with a staratlas.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPad
 - OS: [e.g. iOS12
 - Browser safari

**Additional context**
This appears to be a gemeric problem, not related to trying it on iPad

**Comment by svdwal** [comment]
It doesn't work on the mac either. It is downloading a PDF file, but that file is empty

**Comment by WimDeMeester** [comment]
Thanks for letting us know. There was a wrong configuration on the server. Is fixed now.
