### ISSUE TITLE
Catalogi: objects with double numbers are not displayed

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#770]
The overview of Catalogi (via Menu View) displays all numbers related to a catalog reference.

In case one object has two different numbers assigned in one catalogue, one of both numbers does not appear in the catalogue list. Sometimes the low, somestines the hight number

Example: 
Cr 142 = Cr 143
Cr 199 = Cr 202
![image](https://user-images.githubusercontent.com/12647470/51918743-61afc100-23e2-11e9-989d-9305ee57230f.png)

also at other catalogi, e.g. Harrington 5 = Harrington 17
![image](https://user-images.githubusercontent.com/12647470/51918834-8c017e80-23e2-11e9-99cd-68ea64b459fe.png)
(second number does not appear)

Same situation with STF double stars (reported by Bob hogeveen)
![image](https://user-images.githubusercontent.com/12647470/51918602-21e8d980-23e2-11e9-8923-2de3b0c0b592.png)

**Comment by WimDeMeester** [comment]
This is already fixed in the development version of the laravel version of DeepskyLog.
