### ISSUE TITLE
Responsive design not working on iPhone

### ISSUE THREAD

**Issue by codecube** [DeepskyLog/DeepskyLog#772]
The responsive design is not working in iPhone. It should shrink to size of the screen, but it doesn’t although in a desktop web browser, the resizing is working properly.

![Image](https://i.imgur.com/6hpRhOc.jpg)

I searched a little bit and found this stackoverflow page: https://stackoverflow.com/questions/9386429/simple-bootstrap-page-is-not-responsive-on-the-iphone

It just needed to add following line to the head.php:

echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />";

Already tested locally, the workaround works perfectly.

**Comment by WimDeMeester** [comment]
I have updated DeepskyLog to include the change.  Can you try if everything works as expected?

**Comment by WimDeMeester** [comment]
Indeed, this looks more what it should look like. Closing this issue. Thanks again!
