### ISSUE TITLE
Home page in English?

### ISSUE THREAD

**Issue by estheroetie** [DeepskyLog/DeepskyLog#775]
Would it make sense to switch the default language to English? Many Dutch speakers speak pretty decent English, while English speakers don't often speak Dutch. Switching the default language to English may give a boost to the user base (yay, more observations!).

**Comment by WimDeMeester** [comment]
If you visit http://www.deepskylog.org/, the default page is in English, and you can switch easily to other languages. If you visit http://www.deepskylog.be/ or http://www.deepskylog.nl/ the standard language is Dutch. (deepskylog.fr defaults to French...)

**Comment by estheroetie** [comment]
Oops, sorry for non-issue then

**Comment by WimDeMeester** [comment]
No problem!
