### ISSUE TITLE
Can't download .skylist of all my observations

### ISSUE THREAD

**Issue by ruxandra-valcu** [DeepskyLog/DeepskyLog#778]
When trying to do so, I'm sent to https://www.deepskylog.org/observations.skylist and get the following error:

This site can’t be reachedThe webpage at https://www.deepskylog.org/observations.skylist might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

I can export .csv just fine, but would like to be able to import my observations into SkySafari as well

**Comment by WimDeMeester** [comment]
I think this is a misconfiguration of the server. The strange thing is that I can download the skylist file for objects, but not for observations.

Looking into a solution.

**Comment by WimDeMeester** [comment]
Should be fixed now. There was a small error in the source code. Thanks for reporting the bug!
