### ISSUE TITLE
add_location does not work

### ISSUE THREAD

**Issue by olivierBautista** [DeepskyLog/DeepskyLog#796]
It is impossible to add a location. T
![bug_add_location](https://user-images.githubusercontent.com/61650815/75625486-f032db00-5bbe-11ea-90ae-70db1fccdbba.JPG)
he web page remains empty, both on chrome and on firefox

**Comment by WimDeMeester** [comment]
I tried it also on chome and I see the following page:

![image](https://user-images.githubusercontent.com/7261529/75628291-cb972d00-5bd7-11ea-9e4d-a93a77158894.png)

Does the browser have access to the location? Is javascript turned on? Can you send me the page source code (View -> Developer -> View source in chome)?

**Comment by olivierBautista** [comment]
Access the location is OK, javascript is turned ON.
view-source:https://www.deepskylog.org/index.php?indexAction=add_location

[add_location.txt](https://github.com/DeepskyLog/DeepskyLog/files/4272130/add_location.txt)

**Comment by olivierBautista** [comment]
I have the problem on all the PCs with which I tested the service.

**Comment by olivierBautista** [comment]
same problem on my smartphone

**Comment by WimDeMeester** [comment]
Thanks for the information. You are using the www.deepskylog.org site if I understand correctly. Can you try again and note down the exact date and time you tried. I can look into the logs to see what went wrong...

**Comment by olivierBautista** [comment]
20h06 (france) 
01/03/2020
my ip (ipv6) : 2a01:e0a:23e:3090:79d9:c4a7:e61a:7805
![bug_add_location2](https://user-images.githubusercontent.com/61650815/75632050-8f27f900-5bf8-11ea-83b9-9670c75fd4ef.JPG)

**Comment by WimDeMeester** [comment]
There was indeed a problem with the page to add new locations on the server. Can you try again, I think I have fixed it.

**Comment by olivierBautista** [comment]
Top ! 
it works perfectly.
thank you

**Comment by WimDeMeester** [comment]
Thanks for pointing out the issue!
