### ISSUE TITLE
objects sort by size: minutes and seconds mismatch

### ISSUE THREAD

**Issue by drdenjef** [DeepskyLog/DeepskyLog#801]
**problem**
When you sort a range of objects by size, it will not differentiate between seconds (') and minutes ("). It will instead only look at the number (not accounting for the fact that minutes are larger than seconds). See image below (1st, 3rd and 9th object in list).

**expected solution**
Being able to know that seconds are only 1/60th of minutes and sorting the objects by size appropriately 

![image](https://user-images.githubusercontent.com/23321659/89662332-37429c00-d8d4-11ea-94cb-1e94d664ddf5.png)

**Comment by WimDeMeester** [comment]
Thanks for your bug report.  We will take into account this problem for the next version of DeepskyLog.  At this moment, the current version of DeepskyLog is in maintenance mode, but we are developing a brand new version at this moment.
