### ISSUE TITLE
Add a group field to the gear stuff, 

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#806]
**Is your feature request related to a problem? Please describe.**
When you have a lot of gear, instruments, eyepieces, and so on, or when you observe with other people's stuff, like in a public or private observatory, it is tedious to select the gear, especially eyepieces. By having different groups, you can order your gear and limit the visibility at appropriate times. 

**Describe the solution you'd like**
Add a group field to all the gear entities. The group field can act as an extra selection criterium when selecting gear. It is only a text, nothing complicated as an extra entity.

**Describe alternatives you've considered**
Naming the gear works a bit, but you still have a lot to choose from.
Adding yourself as multiple observers should work fine, but then you need to duplicate other issues, and it is weird.

**Additional context**

**Comment by WimDeMeester** [comment]
Hi @svdwal , can you give an example? What doe you exactly want? As far as I understand, you want an extra field for every eyepiece where you can add a text (the group).  Can you give me an example of such a group? And when adding a new observation, I guess you want to first select the group and then only see the eyepieces that are available in this group.  I guess we want the same for filters and lenses then.

**Comment by WimDeMeester** [comment]
In the upcoming, new version of DeepskyLog, I have added the concept of equipment sets.  More information can be found here:

https://github.com/DeepskyLog/DeepskyLog/discussions/814

The new functionality can already be tested at https://test.deepskylog.org/
