### ISSUE TITLE
Herschel 400 and Herschel 400-II

### ISSUE THREAD

**Issue by torbjornholmqvist** [DeepskyLog/DeepskyLog#815]
Hello,

Something has happened to the Herschel 400 and the Herschel 400-II lists on DeepskyLog. The Herschel 400 now only contains 397 objects and the Herschel 400-II only contains 399 objects. I used to have all H400 and 399 H400-II objects... Something must have happened...

Best regards, 
Torbjörn Holmqvist

**Comment by jefdewit** [comment]
Hi Torbjörn

We are in the process of adapting the NGC list to the Steinicke database. This probably affected the H400 I & II list. I hope to complete the review this week (another 1000 NGCs to go ...). Then we take a look at what went wrong with the H400 lists.

Greetings
Jef

**Comment by jefdewit** [comment]
Hi Torbjörn

H400 I & II as catalog are fixed again. H400 I has only 399 objects because NGC 2371 & 2372 are in fact one object (in DSL).

Greetings
Jef
