### ISSUE TITLE
Problem when adding observations from .csv file

### ISSUE THREAD

**Issue by VedranVrhovac** [DeepskyLog/DeepskyLog#849]
**Describe the bug**
An error appeared when trying to import .csv observation

**To Reproduce**
1. Go to Add -> Observation - Import observation from CSV file - Browse - select .csv file
2. Click on "Import"
3. After 30 seconds following error message appears:
_DeepskyLog
DeepskyLog encountered a problem. Could you please report it to the Developers?
Report problem with error message: DateTimeZone::__construct(): Unknown or bad timezone (undefined)
You can report the problem by sending an email to deepskylog@groups.io.
Thank you._

**Expected behavior**
It should provide report on how many observation were imported in database

**Additional context**
I've tried .csv file that was successfully imported few days ago and it works without problem.
Problematic .csv file is in attachment.

[2023-007.csv](https://github.com/DeepskyLog/DeepskyLog/files/11068399/2023-007.csv)

**Comment by VedranVrhovac** [comment]
It seems that some part of observations from csv file-s are partially imported, but I receive same message.
https://www.deepskylog.org/index.php?indexAction=detail_observation&observation=184459&QobsKey=0&dalm=D
![image](https://user-images.githubusercontent.com/37069629/227706956-c0b6ee6e-234e-49a2-b97a-6c28cecf4f31.png)

**Comment by WimDeMeester** [comment]
There was a problem with one of the locations... The timezone was not correctly set.  I don't know why that is the case at the moment.  I'll try to hunt it down.  Does the CSV still crash or does it work now?

**Comment by VedranVrhovac** [comment]
I was able to upload CSV file with observations. 
Thanks.
